### ISSUE TITLE
immer wieder aufkommendes Abbrechen der Sitzung

### ISSUE THREAD

**Issue by Noob281186** [stackblitz/bolt.new#1296]
### Describe the bug

NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uehx8n

### Steps to reproduce

stabiler werden

### Expected behavior

Es sollte laufen oder wenigen die Fortschritte sichern

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 113385365,
  "usedJSHeapSize": 99086569,
  "jsHeapSizeLimit": 4294705152
}
Username = Noob281186
Chat ID = b378525d455c
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking is here: #2556.
