### ISSUE TITLE
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by rednet1** [stackblitz/bolt.new#1344]
### Describe the bug

when compiling one project i have this error :

NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v2qqan

### Steps to reproduce

compling a new project

### Expected behavior

..

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79194916,
  "usedJSHeapSize": 74639080,
  "jsHeapSizeLimit": 4294705152
}
Username = rednet1
Chat ID = ba7ec10965fc
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2556.
