### ISSUE TITLE
Lost my whole project

### ISSUE THREAD

**Issue by EHC1972** [stackblitz/bolt.new#1380]
### Describe the bug

The agent, encountered some issues and broke the product and its not loading anymore. The results are now missing a ton of work where I spend approx 10M tokens on!

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-znefl9

### Steps to reproduce

20:07:41 [vite] Pre-transform error: Failed to resolve import "react-router-dom" from "src/components/features/FeatureCard.tsx". Does the file exist?
20:07:41 [vite] Internal server error: Failed to resolve import "react-router-dom" from "src/components/features/FeatureCard.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/project/src/components/features/FeatureCard.tsx:2:21
  15 |    window.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;
  16 |  }
  17 |  import { Link } from "react-router-dom";
     |                        ^
  18 |  export function FeatureCard({ title, description, icon: Icon, path, recommended }) {
  19 |    return /* @__PURE__ */ jsxDEV("div", { className: "bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition-shadow duration-300", children: /* @__PURE__ */ jsxDEV("div", { className: "flex items-start space-x-4", children: [
      at TransformPluginContext._formatError (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49304:41)
      at TransformPluginContext.error (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49299:16)
      at normalizeUrl (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64090:23)
      at async eval (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64222:39)
      at async TransformPluginContext.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:64149:7)
      at async PluginContainer.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49145:18)
      at async loadAndTransform (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51978:27)
      at async viteTransformMiddleware (file:///home/project/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:61930:24)
20:08:14 [vite] hmr update /src/components/features/Features.tsx, /src/index.css
20:08:19 [vite] hmr update /src/index.css
20:08:20 [vite] page reload tailwind.config.js
20:08:24 [vite] hmr update /src/App.tsx, /src/index.css
20:08:50 [vite] hmr update /src/App.tsx, /src/index.css (x2)
20:08:57 [vite] hmr update /src/index.css
^C

~/project 1m 24s
❯ npm install

up to date in 480ms

67 packages are looking for funding
  run `npm fund` for details

~/project
❯ 

### Expected behavior

It should reflect the initial product how I designed it.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 79137375,
  "usedJSHeapSize": 62973599,
  "jsHeapSizeLimit": 4294705152
}
Username = eugenecoffie@gmail.com
Chat ID = a5418df89344
```

**Comment by endocytosis** [comment]
Hi @EHC1972, 

This is a known issue and is being tracked here: #39. A workaround is to go to stackblitz.com and login (same credentials as Bolt), click Collections on the left-hand side of the page, and then open Bolt Collections.
