### ISSUE TITLE
Ständige abbruche.

### ISSUE THREAD

**Issue by Noob281186** [stackblitz/bolt.new#1388]
### Describe the bug

Ständige Abbrüche, Projekt muss immer von vorne Abgefangen werdden..

NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uehx8n

### Steps to reproduce

d

### Expected behavior

d

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 59521921,
  "usedJSHeapSize": 53132713,
  "jsHeapSizeLimit": 4294705152
}
Username = Noob281186
Chat ID = f3053565df1d
```

**Comment by Noob281186** [comment]
d

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2556.
