### ISSUE TITLE
erros node

### ISSUE THREAD

**Issue by WillXaibe** [stackblitz/bolt.new#1590]
### Describe the bug

NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fjm6yg

### Steps to reproduce

61 / 5.000
Create a Multusuario Barber Schedule System

### Expected behavior

create system

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/126b9194-c16d-49ea-8b8c-c1e0f793c0b9)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 138259824,
  "usedJSHeapSize": 116802024,
  "jsHeapSizeLimit": 2160066560
}
Username = WillXaibe
Chat ID = deb2bd0e6585
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2556.
