### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ashjdghfjj** [stackblitz/bolt.new#1639]
### Describe the bug

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-swnnhd?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Expected behavior

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Screen Recording / Screenshot

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ro (https://bolt.new/assets/components-B64jh5hJ.js:24:25478)
    at je (https://bolt.new/assets/components-B64jh5hJ.js:24:30669)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27717)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27709)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)
    at kc (https://bolt.new/assets/components-B64jh5hJ.js:24:27514)
    at Ne (https://bolt.new/assets/components-B64jh5hJ.js:24:27401)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
performance.memory = {
  "totalJSHeapSize": 61439480,
  "usedJSHeapSize": 47942900,
  "jsHeapSizeLimit": 4294705152
}
Username = 416906
Chat ID = e99b60eea964
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2556.
