### ISSUE TITLE
Can't even start from scratch

### ISSUE THREAD

**Issue by prescott** [stackblitz/bolt.new#1808]
### Describe the bug

After hours of trying to fix errors, I asked for the Bolt thing to start from scratch. It can't even make it to step 1.

[plugin:vite:import-analysis] Failed to resolve import "./components/Dashboard" from "src/App.tsx". Does the file exist?
/home/project/src/App.tsx:4:26
17 |  import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
18 |  import { Layout } from "./components/Layout";
19 |  import { Dashboard } from "./components/Dashboard";
   |                             ^
20 |  const queryClient = new QueryClient();
21 |  function App() {
    at TransformPluginContext._formatError (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49242:41)
    at TransformPluginContext.error (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49237:16)
    at normalizeUrl (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64033:23)
    at async eval (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64165:39)
    at async TransformPluginContext.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64092:7)
    at async PluginContainer.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49083:18)
    at async loadAndTransform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:51916:27)
    at async viteTransformMiddleware (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61873:24
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.ts.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-viml4m

### Steps to reproduce

Ask to start from scratch.
It fails.

### Expected behavior

Build something useful.

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 128658583,
  "usedJSHeapSize": 124331571,
  "jsHeapSizeLimit": 4294705152
}
Username = prescott
Chat ID = 7e1bcdc73e7d
```

**Comment by endocytosis** [comment]
Hi @prescott, 

If the model is failing to start the project over, it may be necessary to open a new Bolt chat and create a new project. There are some programming challenges that AI can not yet solve automatically. When the AI repeatedly fails on fixing an issue, manual intervention may be required to avoid excessive token consumption. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has some useful information for leveraging the AI most effectively. Hope this helps!
