### ISSUE TITLE
Failed to build and deploy to Netlify

### ISSUE THREAD

**Issue by donvito** [stackblitz/bolt.new#1906]
### Describe the bug

<img width="514" alt="Screenshot 2024-11-10 at 7 26 32 PM" src="https://github.com/user-attachments/assets/414783c9-9679-4b51-afd3-2415e93830fc">

here are the logs

```❯ npm run build

> influencer-search@0.0.0 build
> tsc && vite build

Version 5.6.3
tsc: The TypeScript Compiler - Version 5.6.3                                                                            
                                                                                                                     TS 
COMMON COMMANDS

  tsc
  Compiles the current project (tsconfig.json in the working directory.)

  tsc app.ts util.ts
  Ignoring tsconfig.json, compiles the specified files with default compiler options.

  tsc -b
  Build a composite project in the working directory.

  tsc --init
  Creates a tsconfig.json with the recommended settings in the working directory.

  tsc -p ./path/to/tsconfig.json
  Compiles the TypeScript project located at the specified path.

  tsc --help --all
  An expanded version of this information, showing all possible compiler options
  ```
  
  ```
vite v4.5.5 building for production...
✓ 770 modules transformed.
transforming (773) node_modules/@heroicons/react/index.esm.js[vite:terser] terser not found. Since Vite v3, terser has become an optional dependency. You need to install it.
✓ built in 2.32s
error during build:
Error: terser not found. Since Vite v3, terser has become an optional dependency. You need to install it.
    at loadTerserPath (file:///home/project/node_modules/vite/dist/node/chunks/dep-b2890f90.js:14398:19)
    at Object.renderChunk (file:///home/project/node_modules/vite/dist/node/chunks/dep-b2890f90.js:14434:32)
    at eval (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:25569:40)
    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.f565b097.js:40:22667)

~/project 5s
❯ fatal error: too many writes on closed pipe

goroutine 6 [running]:
runtime.throw({0x9deaa, 0x1e})
        runtime/panic.go:1047 +0x3 fp=0x83aed8 sp=0x83aeb0 pc=0x12250003
os.sigpipe()
        runtime/os_js.go:144 +0x2 fp=0x83aef0 sp=0x83aed8 pc=0x13b70002
os.epipecheck(...)
        os/file_unix.go:224
os.(*File).Write(0x80c020, {0x191e000, 0x1bf7e, 0x1c000})
        os/file.go:183 +0x2d fp=0x83af78 sp=0x83aef0 pc=0x1607002d
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:99 +0x7 fp=0x83afe0 sp=0x83af78 pc=0x1f630007
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x83afe8 sp=0x83afe0 pc=0x14070001
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:97 +0x1e

goroutine 1 [chan receive]:
runtime.gopark(0xb66b0, 0xaecad8, 0xe, 0x17, 0x2)
        runtime/proc.go:381 +0x28 fp=0x85f918 sp=0x85f8f0 pc=0x124c0028
runtime.chanrecv(0xaeca80, 0x85fa48, 0x1)
        runtime/chan.go:583 +0x7f fp=0x85f9a0 sp=0x85f918 pc=0x106d007f
runtime.chanrecv1(0xaeca80, 0x85fa48)
        runtime/chan.go:442 +0x2 fp=0x85f9c8 sp=0x85f9a0 pc=0x106b0002
syscall.fsCall({0x8fb39, 0x4}, {0x85fb30, 0x5, 0x5})
        syscall/fs_js.go:520 +0x13 fp=0x85fa98 sp=0x85f9c8 pc=0x159f0013
syscall.Read(0x0, {0x8be000, 0x4000, 0x4000})
        syscall/fs_js.go:388 +0xb fp=0x85fb88 sp=0x85fa98 pc=0x159b000b
internal/poll.ignoringEINTRIO(...)
        internal/poll/fd_unix.go:794
internal/poll.(*FD).Read(0x830060, {0x8be000, 0x4000, 0x4000})
        internal/poll/fd_unix.go:163 +0x57 fp=0x85fc20 sp=0x85fb88 pc=0x15ee0057
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0x80c018, {0x8be000, 0x4000, 0x4000})
        os/file.go:118 +0x12 fp=0x85fc98 sp=0x85fc20 pc=0x16050012
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:134 +0x46 fp=0x85fde0 sp=0x85fc98 pc=0x1f600046
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:240 +0x9e fp=0x85ff88 sp=0x85fde0 pc=0x1f59009e
runtime.main()
        runtime/proc.go:250 +0x32 fp=0x85ffe0 sp=0x85ff88 pc=0x12460032
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x85ffe8 sp=0x85ffe0 pc=0x14070001

goroutine 2 [force gc (idle)]:
runtime.gopark(0xb6848, 0x3c65d0, 0x11, 0x14, 0x1)
        runtime/proc.go:381 +0x28 fp=0x828fb8 sp=0x828f90 pc=0x124c0028
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.forcegchelper()
        runtime/proc.go:305 +0x1f fp=0x828fe0 sp=0x828fb8 pc=0x1249001f
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x828fe8 sp=0x828fe0 pc=0x14070001
created by runtime.init.5
        runtime/proc.go:293 +0x2

goroutine 3 [GC sweep wait]:
runtime.gopark(0xb6848, 0x3c6960, 0xc, 0x14, 0x1)
        runtime/proc.go:381 +0x28 fp=0x829798 sp=0x829770 pc=0x124c0028
runtime.goparkunlock(...)
        runtime/proc.go:387
runtime.bgsweep(0x82e000)
        runtime/mgcsweep.go:319 +0x21 fp=0x8297d0 sp=0x829798 pc=0x11790021
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x2 fp=0x8297e0 sp=0x8297d0 pc=0x110d0002
runtime.goexit()
        runtime/asm_wasm.s:399 +0x1 fp=0x8297e8 sp=0x8297e0 pc=0x14070001
created by runtime.gcenable
        runtime/mgc.go:178 +0x8

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xb6848, 0x3c6ba0, 0xd, 0x14, 0x2)
  ```

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hyjmhc

### Steps to reproduce

1. Click Deploy 
2. It will show this error

### Expected behavior

App to be deployed in Netlify

### Screen Recording / Screenshot

<img width="514" alt="Screenshot 2024-11-10 at 7 26 32 PM" src="https://github.com/user-attachments/assets/c5e9f6d7-360f-4db4-8d55-b0a5916a9a23">

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 92532551,
  "usedJSHeapSize": 81800519,
  "jsHeapSizeLimit": 4294705152
}
Username = donvito
Chat ID = 61d2cf2f4b99
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by donvito** [comment]
I was able to fix the issue by prompting it. I think it still needs to be fixed for end users since they are not aware how to prompt it.

<img width="519" alt="Screenshot 2024-11-10 at 7 43 49 PM" src="https://github.com/user-attachments/assets/ce1faea9-82a1-4e14-9f8e-424bcb7d77b4">

**Comment by donvito** [comment]
I am able to deploy to Netlify but not sure how to claim the URL. It doesn't show now in the chat.

**Comment by endocytosis** [comment]
Hi @donvito, 

Really appreciate the detailed feedback here! We are tracking the build failure issue here: #2019. We are tracking the missing claim URL issue here: #2020.
