### ISSUE TITLE
Explosion of Bolt :)

### ISSUE THREAD

**Issue by nicolas-geysse** [stackblitz/bolt.new#2365]
### Describe the bug

Hello,
While using this (great) app I got that error :

Application Error
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Le (https://bolt.new/assets/components-B64jh5hJ.js:22:17522)
    at Object.ec [as useCallback] (https://bolt.new/assets/components-B64jh5hJ.js:22:21045)
    at O.useCallback (https://bolt.new/assets/index-fw5NnR3n.js:9:5633)
    at I (https://bolt.new/assets/stripIndent-YObSZ0C4.js:1:206)
    at OP (https://bolt.new/assets/_index-BDOX5lQw.js:66:4112)
    at https://bolt.new/assets/_index-BDOX5lQw.js:66:4053
    at Array.flatMap (<anonymous>)
    at https://bolt.new/assets/_index-BDOX5lQw.js:66:4007
    at Vo (https://bolt.new/assets/components-B64jh5hJ.js:22:16948)
    at Ji (https://bolt.new/assets/components-B64jh5hJ.js:24:3134)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-7k5rnz

### Steps to reproduce

It happens during a prompt, I have no clue why, but the all interface exploded !

### Expected behavior

Not to explode ? :)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 114854736,
  "usedJSHeapSize": 90593068,
  "jsHeapSizeLimit": 4294705152
}
Username = Niko
Chat ID = bc3411b9d013
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are tracking this issue here: #2348.
