### ISSUE TITLE
beug

### ISSUE THREAD

**Issue by mikelkarim** [stackblitz/bolt.new#2369]
### Describe the bug

L'erreur `SyntaxError: le module demandé « /node_modules/lucide-react/dist/esm/lucide-react.js?v=11382feb » ne fournit pas d'exportation nommé « Wave »` signifie que vous essayez d'importer un composant ou un module `Wave` à partir de `lucide-react`, mais celui-ci n'est pas exporté de cette manière par la bibliothèque. Pour résoudre ce problème, voici quelques étapes à suivre : 1. **Vérifiez la documentation** : Consultez la documentation de `lucide-react` pour vérifier si le composant `Wave` existe dans cette bibliothèque. Il est possible que ce composant ait été renommé ou déplacé dans une autre version. La documentation vous donnera les exportations correctes à utiliser. 2. **Vér

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-bddfwc

### Steps to reproduce

at FunctionScope.findVariable (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:5277:38)
    at FunctionBodyScope.findVariable (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:5277:38)
    at Identifier.bind (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:5060:40)
    at CallExpression.bind (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:2876:28)
    at CallExpression.bind (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:11260:15)

~/project 16s
❯ 

### Expected behavior

application

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82853663,
  "usedJSHeapSize": 65953143,
  "jsHeapSizeLimit": 4294705152
}
Username = mikelkarim
Chat ID = 9f87eb09f5af
```

### Additional context

Error:
```
Failed building the project. Make sure the build command is correct and try again.
```

**Comment by mikelkarim** [comment]
comment resoudre
