### ISSUE TITLE
Importing the project resulted in an error.

### ISSUE THREAD

**Issue by arschlochnop** [stackblitz/bolt.new#260]
### Describe the bug

I get an error message when I import the project. The error message is as follows:
```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fe (https://bolt.new/assets/components-g8_Fbz61.js:24:33638)
    at np (https://bolt.new/assets/components-g8_Fbz61.js:22:22233)
    at iB (https://bolt.new/assets/_index-BSckk7Xf.js:3:685)
    at https://bolt.new/assets/_index-BSckk7Xf.js:3:754
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BSckk7Xf.js:3:743
    at iB (https://bolt.new/assets/_index-BSckk7Xf.js:3:685)
    at https://bolt.new/assets/_index-BSckk7Xf.js:3:754
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BSckk7Xf.js:3:743
```

### Link to the Bolt URL that caused the error

https://bolt.new/~/github-zy5nye

### Steps to reproduce

1. open url https://bolt.new/~/github-zy5nye 

### Expected behavior

Project file loaded successfully.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
performance.memory = {
  "totalJSHeapSize": 193307800,
  "usedJSHeapSize": 174770184,
  "jsHeapSizeLimit": 4294705152
}
Chat ID = 2a744bde9038
```

**Comment by d-vlasov** [comment]
hey I think I got this because I tried to use this option on the free plan . After upgraded to paid it worked

**Comment by lkorba** [comment]
It happens to me very often on a paid plan, burning my tokens pretty quickly (every couple of changes I make it just pops up and after refresh I lose last progress)
