### ISSUE TITLE
ERR_INVALID_STATE

### ISSUE THREAD

**Issue by akshaynmhc** [stackblitz/bolt.new#266]
### Describe the bug

TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at ReadableByteStreamController.close (node:internal/webstreams/readablestream:1156:13)
    at close (D:\llm\bolt\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.development.js:143:15)
    at flushCompletedQueues (D:\llm\bolt\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6906:9)
    at abort (D:\llm\bolt\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6951:7)
    at EventTarget.listener (D:\llm\bolt\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.browser.development.js:7000:9)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:825:20)
    at EventTarget.dispatchEvent (node:internal/event_target:760:26)
    at abortSignal (node:internal/abort_controller:370:10)
    at AbortController.abort (node:internal/abort_controller:392:5)
    at EventTarget.abort (node:internal/deps/undici/undici:5038:21)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:825:20)
    at EventTarget.dispatchEvent (node:internal/event_target:760:26)
    at abortSignal (node:internal/abort_controller:370:10)
    at AbortController.abort (node:internal/abort_controller:392:5)
    at ServerResponse.<anonymous> (D:\llm\bolt\node_modules\.pnpm\@remix-run+dev@2.12.1_@remix-run+react@2.12.1_sass-embedded@1.79.4_typescript@5.6.3_vite@5.4.8_wrangler@3.80.2\node_modules\@remix-run\dev\dist\vite\node-adapter.js:46:40)
    at ServerResponse.emit (node:events:519:28)
    at ServerResponse.emit (node:domain:488:12)
    at emitCloseNT (node:_http_server:1020:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_INVALID_STATE'
}

### Link to the Bolt URL that caused the error

http://localhost:5173/chat/astro-mdx-blog

### Steps to reproduce

Run pnpn run dev command and start generating UI

### Expected behavior

Run pnpn run dev command and start generating UI

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/da74bafc-b569-4532-930e-dabcc00b29d5)

### Platform

- OS: Windows
- Browser: Google Chrome Canary
- Version: latest

**Comment by NAMEKDSUN** [comment]
me too

**Comment by NAMEKDSUN** [comment]
Have you fixed the bug yet?
