### ISSUE TITLE
Installation and Run errors

### ISSUE THREAD

**Issue by DavidWaichari** [stackblitz/bolt.new#2693]
### Describe the bug

$ pnpm run dev

> bolt@ dev C:\Users\David\Desktop\bolt.new
> remix vite:dev

*** Received structured exception #0xc0000005: access violation; stack: 7ff96cb332f7 7ff7119d337b 7ff7119d3443 7ff7119c74bc 7ff7119c7467 7ff711247d5e 7ff71124806f 7ff710131706 7ff7101314ea 7ff7113bf97f 7ff7113c6b36 7ff7113bfe9c 7ff7113c6b36 7ff7113bd80c 7ff710121551 7ff712aa8bff 7ff974217373 7ff9760fcc90
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.       
    at #assembleAndUpdateConfig (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:3521:16)
    at async #waitForReady (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9235:5)
    at async Miniflare2._getProxyClient (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9359:5)
    at async Miniflare2.getBindings (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9378:25)
    at async getPlatformProxy (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0\node_modules\wrangler\wrangler-dist\cli.js:210522:20)
    at async configureServer (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///C:/Users/David/Desktop/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:750:27)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Users/David/Desktop/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async _createServer (file:///C:/Users/David/Desktop/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62977:18)
    at async dev (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at async Object.viteDev (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\commands.js:220:3)
    at async Object.run (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.

David@DESKTOP-URPABO6 MINGW64 ~/Desktop/bolt.new (main)
$

### Link to the Bolt URL that caused the error

Local cloning

### Steps to reproduce

Clone, pnpm install, pnpm run dev

### Expected behavior

The app to run smoothly when I run pnpm run dev

### Screen Recording / Screenshot

$ pnpm run dev

> bolt@ dev C:\Users\David\Desktop\bolt.new
> remix vite:dev

*** Received structured exception #0xc0000005: access violation; stack: 7ff96cb332f7 7ff7119d337b 7ff7119d3443 7ff7119c74bc 7ff7119c7467 7ff711247d5e 7ff71124806f 7ff710131706 7ff7101314ea 7ff7113bf97f 7ff7113c6b36 7ff7113bfe9c 7ff7113c6b36 7ff7113bd80c 7ff710121551 7ff712aa8bff 7ff974217373 7ff9760fcc90
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.       
    at #assembleAndUpdateConfig (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Mutex.runWith (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:3521:16)
    at async #waitForReady (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9235:5)
    at async Miniflare2._getProxyClient (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9359:5)
    at async Miniflare2.getBindings (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9378:25)
    at async getPlatformProxy (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0\node_modules\wrangler\wrangler-dist\cli.js:210522:20)
    at async configureServer (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///C:/Users/David/Desktop/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:750:27)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Users/David/Desktop/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async _createServer (file:///C:/Users/David/Desktop/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62977:18)
    at async dev (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at async Object.viteDev (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\commands.js:220:3)
    at async Object.run (C:\Users\David\Desktop\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.

David@DESKTOP-URPABO6 MINGW64 ~/Desktop/bolt.new (main)
$

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Windows PC

### Additional context

None

**Comment by endocytosis** [comment]
Appreciate the feedback! Unfortunately, we don't have the resources right now to offer support for running the open-source version of Bolt locally. This page [here](https://github.com/stackblitz/bolt.new/blob/main/CONTRIBUTING.md) has instructions on configuring Bolt locally. Hope this helps!
