### ISSUE TITLE
many errors for save chat

### ISSUE THREAD

**Issue by codessauro** [stackblitz/bolt.new#2744]
### Describe the bug

/api/deploy/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/api/chats/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/api/chats/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
/api/chats/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
main.tsx:3 Uncaught SyntaxError: The requested module '/src/App.tsx' does not provide an export named 'default' (at main.tsx:3:8)

### Link to the Bolt URL that caused the error

https://bolt.new/~/node-uam981

### Steps to reproduce

/api/deploy/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
/api/chats/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
/api/chats/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
/api/chats/33767698:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
stackblitz.com/api/projects/node-uam981:1 
        
        
       Failed to load resource: net::ERR_FAILED
_index-CANs_fem.js:41 TypeError: Failed to fetch
    at Lh (_index-CANs_fem.js:65:6498)
    at async GI (_index-CANs_fem.js:65:5992)
    at async #u (_index-CANs_fem.js:41:618)
#u @ _index-CANs_fem.js:41
main.tsx:3 Uncaught SyntaxError: The requested module '/src/App.tsx' does not provide an export named 'default' (at main.tsx:3:8)

### Expected behavior

Not save github repository or chat

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/9ae9dd73-9dd9-43e2-8dad-b196167c06a1)

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 52137198,
  "usedJSHeapSize": 46486814,
  "jsHeapSizeLimit": 4294705152
}
Username = codessauro
Chat ID = 69c5ea3757c7
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking it here: #2762.
