### ISSUE TITLE
Having problem connecting MongoDB

### ISSUE THREAD

**Issue by PathSynch-CEO** [stackblitz/bolt.new#2975]
### Describe the bug

[plugin:vite:import-analysis] Failed to resolve import "mongodb" from "src/services/mongodb.ts". Does the file exist?
/home/project/src/services/mongodb.ts:1:50
1  |  import { MongoClient, ServerApiVersion } from "mongodb";
   |                                                 ^
2  |  import { MONGODB_CONFIG } from "../config/mongodb";
3  |  class MongoDBService {
    at TransformPluginContext._formatError (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49242:41)
    at TransformPluginContext.error (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49237:16)
    at normalizeUrl (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64033:23)
    at async eval (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64165:39)
    at async TransformPluginContext.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64092:7)
    at async PluginContainer.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49083:18)
    at async loadAndTransform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:5191

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jgzdqp

### Steps to reproduce

Trying to render the project

### Expected behavior

The website should work

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 126912020,
  "usedJSHeapSize": 101058796,
  "jsHeapSizeLimit": 1998061568
}
Username = Path
Chat ID = 7cc94c804522
```

**Comment by endocytosis** [comment]
Apologies for the frustration! Unfortunately, we don't have the resources to offer programming advice on individual projects. However, the [Bolt Help Center](https://support.bolt.new) has a number of resources on using Bolt most effectively, including database integration.
