### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by yujioucheng** [stackblitz/bolt.new#348]
### Describe the bug

应用程序错误
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at to (https://bolt.new/assets/components-g8_Fbz61.js:24:25478)
    at je (https://bolt.new/assets/components-g8_Fbz61.js:24:30669)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27717)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vjeute

### Steps to reproduce

应用程序错误
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at to (https://bolt.new/assets/components-g8_Fbz61.js:24:25478)
    at je (https://bolt.new/assets/components-g8_Fbz61.js:24:30669)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27717)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

### Expected behavior

应用程序错误
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at to (https://bolt.new/assets/components-g8_Fbz61.js:24:25478)
    at je (https://bolt.new/assets/components-g8_Fbz61.js:24:30669)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27717)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

### Platform

```
Browser name = Chrome
Full version = 126.0.0.0
Major version = 126
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
performance.memory = {
  "totalJSHeapSize": 56375256,
  "usedJSHeapSize": 50955312,
  "jsHeapSizeLimit": 4294705152
}
Username = yujioucheng
Chat ID = 167feac4a7a8
```

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking is here: #2556.
