### ISSUE TITLE
Failed to persist chat messages

### ISSUE THREAD

**Issue by endocytosis** [stackblitz/bolt.new#3631]
**Issue:** Failed to persist chat message error message. Collecting similar cases with network status codes for further investigation.

**Comment by endocytosis** [comment]
![image](https://github.com/user-attachments/assets/05930fc1-28f8-475b-86c6-68927b8e1469)
![image](https://github.com/user-attachments/assets/0d5f3c71-7e2a-45f0-b018-0ee1903bc579)

**Comment by Jpubli** [comment]
Here also!! every 1sec

**Comment by TC-ConTech** [comment]
Failed to persist the chat messages

Failed to persist the chat messages

Application Error
TypeError: Failed to fetch
    at qc (https://bolt.new/assets/components-Bjm90aTH.js:97:950)
    at async oh (https://bolt.new/assets/components-Bjm90aTH.js:150:4133)
    at async p (https://bolt.new/assets/components-Bjm90aTH.js:150:1619)
I've lost millions of tokens trying to resolve this. Don't know what to do here.

**Comment by assortables** [comment]
I am seeing this issue when importing the StackBlitz project into Bolt.  Because there is no persist in the chat messages there are no rollback features offered.

**Comment by Jpubli** [comment]
I decided to move to Windsurf AI. Bolt is a nice product but still have a lot to do in regards of failures and token consumption

**Comment by Herdianta** [comment]
Also encounter this problem. The chats become missing also. please solve this.

![Image](https://github.com/user-attachments/assets/889f4605-09ac-47bb-8044-0169c44f2f47)

**Comment by RealtorFlow** [comment]
I'm still having this.  prevents me from being able to rollback too.
