### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by Coding-xiaobo** [stackblitz/bolt.new#3944]
### Describe the bug

node：v20.15.1
OS: linux

errno: -32
code: 'EPIPE',
syscall: 'write'

### Link to the Bolt URL that caused the error

no

### Steps to reproduce

1. pnpm install 
![image](https://github.com/user-attachments/assets/4168d798-fc5f-4124-b286-7c3fcfdd6f89)
2. pnpm run dev

error:

> bolt@ dev /home/10328097/下载/bolt.new-main
> remix vite:dev

Proxy environment variables detected. We'll use your proxy for fetch requests.
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:953:11)
    at Socket._write (node:net:965:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at Runtime.updateConfig (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:5051:26)
    at async #assembleAndUpdateConfig (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9171:30)
    at async Mutex.runWith (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:3521:16)
    at async #waitForReady (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9235:5)
    at async Miniflare2._getProxyClient (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9359:5)
    at async Miniflare2.getBindings (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9378:25)
    at async getPlatformProxy (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0/node_modules/wrangler/wrangler-dist/cli.js:210522:20)
    at async configureServer (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///home/10328097/%E4%B8%8B%E8%BD%BD/bolt.new-main/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/plugin.js:750:27)
    at async Promise.all (index 3)
    at async resolveConfig (file:///home/10328097/%E4%B8%8B%E8%BD%BD/bolt.new-main/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async _createServer (file:///home/10328097/%E4%B8%8B%E8%BD%BD/bolt.new-main/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62977:18)
    at async dev (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/dev.js:39:16)
    at async Object.viteDev (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/cli/commands.js:220:3)
    at async Object.run (/home/10328097/下载/bolt.new-main/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/cli/run.js:271:7) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
 ELIFECYCLE  Command failed with exit code 1.

### Expected behavior

pnpm run dev successfully

### Platform

- OS: linux
- Browser: Chrome
- Version: [e.g. 91.1]

**Comment by DUT-MZY** [comment]
the same

**Comment by JackBiggers** [comment]
having a similar issue it just says  Error: write EPIPE
