### ISSUE TITLE
Error constantly appearing without a fix

### ISSUE THREAD

**Issue by Sid3106** [stackblitz/bolt.new#4119]
### Describe the bug

I have tried to create a datagrid. But it is throwing error. I am not a professional coder and understand little of coding. Despite attempting the fix multiple times, the error stays. My application is working fine. It is generating preview and all functionalities are working as expected, but this error just stays in the chat box.

Attempts to fix this has consumed a lot of credits and it still appears as it is. I am not sure how to get rid of this. The error is:

"Warning: Each child in a list should have a unique "key" prop.%s%s See https://reactjs.org/link/warning-keys for more information.%s"" Check the render method of `ClientGrid`."""" at div at ClientGrid (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--fc837ba8.local-credentialless.webcontainer-api.io/src/components/dashboard/ClientGrid.tsx:26:20) at RenderedRoute (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--fc837ba8.local-credentialless.webcontainer-api.io/node_modules/.vite/deps/react-router-dom.js?v=0fc10dfe:4069:5) at Routes (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--fc837ba8.local-credentialless.webcontainer-api.io/node_modules/.vite/deps/react-router-dom.js?v=0fc10dfe:4539:5) at div at div at AppContent at Router (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--fc837ba8.local-credentialless.webcontainer-api.io/node_modules/.vite/deps/react-router-dom.js?v=0fc10dfe:4482:15) at BrowserRouter (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--fc837ba8.local-credentialless.webcontainer-api.io/node_modules/.vite/deps/react-router-dom.js?v=0fc10dfe:5228:5) at AuthGuard (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--fc837ba8.local-credentialless.webcontainer-api.io/src/components/AuthGuard.tsx:20:29) at AuthProvider (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--fc837ba8.local-credentialless.webcontainer-api.io/src/contexts/AuthContext.tsx:21:32) at App"

at printWarning (/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=0fc10dfe:64:38)
   at error (/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=0fc10dfe:48:15)
   at validateExplicitKey (/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=0fc10dfe:724:13)
   at validateChildKeys (/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=0fc10dfe:737:19)
   at jsxWithValidation (/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=0fc10dfe:855:19)
   at ClientGrid (/src/components/dashboard/ClientGrid.tsx:122:32)
   at renderWithHooks (/node_modules/.vite/deps/chunk-6VWAHX6D.js?v=0fc10dfe:11548:26)
   at updateFunctionComponent (/node_modules/.vite/deps/chunk-6VWAHX6D.js?v=0fc10dfe:14582:28)

It stays there in my chat box forever. Please help me in fixing this. Thanks. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-cmcb7pqz

### Steps to reproduce

It stays in my chatbox all the time. 

### Expected behavior

When clicked on Attempt fix, it should atleast tell me where the problem lies or what I should be doing to fix it. It consumes a lot of credit and result stays the same.

### Screen Recording / Screenshot

<img width="1419" alt="Screenshot 2024-12-13 at 7 00 45 AM" src="https://github.com/user-attachments/assets/5de83c4c-254a-46bb-910d-3427e16d9fb6" />

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 75982216,
  "usedJSHeapSize": 73552868,
  "jsHeapSizeLimit": 2197815296
}
Username = Sid3106
Chat ID = c171f1d9d950
```

**Comment by YendiGB** [comment]
I am also stuck in an endless loop of attempting to fix an error it caused, blew almost 5000k tokens there already. I think it's a major issue. I wonder if they're actually going to do anything to solve it.
