### ISSUE TITLE
TYPE ERROR

### ISSUE THREAD

**Issue by Errolpd2** [stackblitz/bolt.new#4334]
### Describe the bug

TypeError: Cannot read properties of null (reading 'type')
   at Ln.<anonymous> (chrome-extension://egjidjbpglichdcondbcbdnbeeppgdph/inpage.js:247:166789)
   at Generator.next (<anonymous>)
   at ae (chrome-extension://egjidjbpglichdcondbcbdnbeeppgdph/inpage.js:247:165677)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-usakaphm

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

TypeError: Cannot read properties of null (reading 'type')
   at Ln.<anonymous> (chrome-extension://egjidjbpglichdcondbcbdnbeeppgdph/inpage.js:247:166789)
   at Generator.next (<anonymous>)
   at ae (chrome-extension://egjidjbpglichdcondbcbdnbeeppgdph/inpage.js:247:165677)

### Expected behavior

The dashboard keeps showing error code and I keep hitting the FIX button and it then says it's fixed it but then the error notification pops up continually I have done this 3-4 times it's using up my credits and not fixing the problem also no preview is available just blank screen please advise?

### Screen Recording / Screenshot

![Capture](https://github.com/user-attachments/assets/979a8068-4ae2-4c82-9d74-169f65d4436f)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 128240762,
  "usedJSHeapSize": 85429938,
  "jsHeapSizeLimit": 2197815296
}
Username = errolpd2
Chat ID = db31680e8676
```

### Additional context

Please advise on how to fix this error it just keeps popping up even after I hit the fix button it doesn't fix the problem thank you so much hope to hear back soon

**Comment by Errolpd2** [comment]
I was expecting to see a preview after Bolt had created the coding but I just keep getting error code without error fix completeting thankyou

**Comment by Labhk** [comment]
I don't what prompts u gave it, I checked ur code in stackblitz, there are many file missing and the file path are wrong
![image](https://github.com/user-attachments/assets/d7e4ebaa-0b8d-4932-99aa-a652acd1a325)

it should look like this
![image](https://github.com/user-attachments/assets/d5f94888-da9e-4e39-879c-65d3641d18fb)
