### ISSUE TITLE
Error "Could not resolve"

### ISSUE THREAD

**Issue by joansafr** [stackblitz/bolt.new#4362]
### Describe the bug

Im getting this error when I build he project in the bolt command line:

```
Could not resolve "./OrderStatusBadge.vue" from "home/project/src/components/dashboard/orders/mobile/OrderCard.vue?vue&type=script&setup=true&lang.ts"
file: /home/project/home/project/src/components/dashboard/orders/mobile/OrderCard.vue?vue&type=script&setup=true&lang.ts
    at getRollupError (file:///home/project/node_modules/rollup/dist/es/shared/parseAst.js:558:41)
    at Module.error (file:///home/project/node_modules/rollup/dist/es/shared/parseAst.js:554:42)
    at ModuleLoader.handleInvalidResolvedId (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:20108:37)
    at eval (file:///home/project/node_modules/rollup/dist/es/shared/node-entry.js:20068:26)
```

There is a bug because that file exist... I opened in Stackblitz and it work very well, just run:

`npm run build`

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fhi6vz

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

1. Go to the bolt terminal
2. Run the command "npm run build"

### Expected behavior

It must build successfully.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 86842847,
  "usedJSHeapSize": 81590603,
  "jsHeapSizeLimit": 4294705152
}
Username = joansafr
Chat ID = 5291f610eca0
```

**Comment by Labhk** [comment]
Hi,
Your project is not public, I can't open it.
