### ISSUE TITLE
Memory limit capacity

### ISSUE THREAD

**Issue by SwizJoshua** [stackblitz/bolt.new#4418]
### Describe the bug

Creating an app and website

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-vqyu6jfa

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

1

### Expected behavior

No memory limit

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 42100000,
  "usedJSHeapSize": 42100000,
  "jsHeapSizeLimit": 521000000
}
```

### Additional context

Error:
```
out-of-memory: RuntimeError: unreachable
    at wasm://wasm/a36bee7a:wasm-function[10]:0x1f9f
    at wasm://wasm/a36bee7a:wasm-function[7]:0x1e60
    at _0x2e513f (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/filesystem-worker.c8c182a3.js:1:351974)
    at _0x37b71a (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/filesystem-worker.c8c182a3.js:1:352709)
    at async _0x313909._initSlabAsync (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/filesystem-worker.c8c182a3.js:1:355285)
    at async _0x313909.create (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/filesystem-worker.c8c182a3.js:1:353132)
    at async _0x37556f.init (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/filesystem-worker.c8c182a3.js:1:493823)
```

**Comment by SwizJoshua** [comment]
import StockPerformanceChart from '@/components/StockPerformanceChart'
import MarketingCampaigns from '@/components/MarketingCampaigns'
import KeyMetrics from '@/components/KeyMetrics'

export default function DashboardPage() {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-3xl font-bold mb-6">Dashboard</h1>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <StockPerformanceChart />
        <MarketingCampaigns />
        <KeyMetrics />
      </div>
    </div>
  )
}
