### ISSUE TITLE
An unexpected error occured - I have the PRO200 plan and bought additional tokens

### ISSUE THREAD

**Issue by habste42** [stackblitz/bolt.new#4480]
### Describe the bug

TypeError: Cannot read properties of undefined (reading 'available')
    at https://bolt.new/assets/_index-DnJyLzC1.js:88:114919
    at Nh (https://bolt.new/assets/components-BPQqK2_k.js:22:17831)
    at cj (https://bolt.new/assets/components-BPQqK2_k.js:24:3288)
    at bj (https://bolt.new/assets/components-BPQqK2_k.js:24:2471)
    at $i (https://bolt.new/assets/components-BPQqK2_k.js:24:2002)
    at Vk (https://bolt.new/assets/components-BPQqK2_k.js:24:47989)
    at Uk (https://bolt.new/assets/components-BPQqK2_k.js:24:40384)
    at Tk (https://bolt.new/assets/components-BPQqK2_k.js:24:40293)
    at Ik (https://bolt.new/assets/components-BPQqK2_k.js:24:40140)
    at Nk (https://bolt.new/assets/components-BPQqK2_k.js:24:36425)

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vue-jtdetfei?showPricing=true

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Just started a new project and wanted to develop a new feature
All 10.000.000 Tokens have been gone within a second

### Expected behavior

All 10.000.000 Tokens have been gone within a second

### Screen Recording / Screenshot

Component stack: 
    at https://bolt.new/assets/_index-DnJyLzC1.js:88:114513
    at https://bolt.new/assets/_index-DnJyLzC1.js:88:121476
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:1:1119)
    at div
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:97:146)
    at https://bolt.new/assets/_index-DnJyLzC1.js:145:9492
    at https://bolt.new/assets/_index-DnJyLzC1.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-DnJyLzC1.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DnJyLzC1.js:145:39818)
    at Index

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 51861100,
  "usedJSHeapSize": 49142648,
  "jsHeapSizeLimit": 2160066560
}
```

### Additional context

Error:
```
TypeError: Cannot read properties of undefined (reading 'available')
    at https://bolt.new/assets/_index-DnJyLzC1.js:88:114919
    at Nh (https://bolt.new/assets/components-BPQqK2_k.js:22:17831)
    at cj (https://bolt.new/assets/components-BPQqK2_k.js:24:3288)
    at bj (https://bolt.new/assets/components-BPQqK2_k.js:24:2471)
    at $i (https://bolt.new/assets/components-BPQqK2_k.js:24:2002)
    at Vk (https://bolt.new/assets/components-BPQqK2_k.js:24:47989)
    at Uk (https://bolt.new/assets/components-BPQqK2_k.js:24:40384)
    at Tk (https://bolt.new/assets/components-BPQqK2_k.js:24:40293)
    at Ik (https://bolt.new/assets/components-BPQqK2_k.js:24:40140)
    at Nk (https://bolt.new/assets/components-BPQqK2_k.js:24:36425)
Component stack: 
    at https://bolt.new/assets/_index-DnJyLzC1.js:88:114513
    at https://bolt.new/assets/_index-DnJyLzC1.js:88:121476
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:1:1119)
    at div
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:97:146)
    at https://bolt.new/assets/_index-DnJyLzC1.js:145:9492
    at https://bolt.new/assets/_index-DnJyLzC1.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-DnJyLzC1.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DnJyLzC1.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:97:146)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-COlor5d7.js:1:1119)
    at Layout (https://bolt.new/assets/root-CcPCgfT6.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at RenderErrorBoundary (https://bolt.new/assets/index-BkkrDsoJ.js:36:3227)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at RemixErrorBoundary (https://bolt.new/assets/components-BPQqK2_k.js:121:84)
    at RemixBrowser (https://bolt.new/assets/entry.client-Pqxp-6g8.js:19:1820)
```

**Comment by AriPerkkio** [comment]
Hey @habste42, thanks for the report.

This issue should be fixed now. Could you check if it works now on your end?

**Comment by habste42** [comment]
Cool. I lost 10.000.000 tokens as a PRO200 member...
