### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by Bunker923** [stackblitz/bolt.new#4521]
### Describe the bug

Não está a terminar de completar as funçoes, está sempre dando erro de plugins

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-hxxedwm2

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Veja o erro de plugins

### Expected behavior

Erro

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 124600040,
  "usedJSHeapSize": 100646556,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at li
    at ol
    at div
    at div (https://bolt.new/assets/_index-NyEmdF5V.js:69:668)
    at Markdown$1 (https://bolt.new/assets/_index-NyEmdF5V.js:43:13804)
    at https://bolt.new/assets/_index-NyEmdF5V.js:69:541
    at div
    at https://bolt.new/assets/_index-NyEmdF5V.js:69:1719
    at div
    at div
    at div
    at div
    at div
    at https://bolt.new/assets/_index-NyEmdF5V.js:88:9914
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at div
    at div
    at div
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-NyEmdF5V.js:145:9492
    at https://bolt.new/assets/_index-NyEmdF5V.js:145:26365
    at Chat (https://bolt.new/assets/_index-NyEmdF5V.js:145:25147)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-NyEmdF5V.js:145:39818)
    at Index$1
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at Layout (https://bolt.new/assets/root-Dgim_hb8.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
```

**Comment by AriPerkkio** [comment]
Hey @Bunker923, thanks for the report.

We'll get this fixed soon, but meanwhile you can proceed by disabling the browser extension that your are using to translate the page into different language. The browser extension is breaking Bolt here.

**Comment by AriPerkkio** [comment]
This bug is now fixed.
