### ISSUE TITLE
échec la connexion projet bolt.new à Supabase 

### ISSUE THREAD

**Issue by tandia00** [stackblitz/bolt.new#4573]
### Describe the bug

J'ai travaillé une copie de mon projet de Bolt, quand j'ai essayé de connecter mon projet copié à Supabase, ça a bugué, et supprimé mon projet original, malgré cela, ça pas marché.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-weahvp76

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at button
    at https://bolt.new/assets/login-CwjdxPzR.js:1:40172
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17807
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:4487
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17807
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:4487
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:38662
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:4734
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:2869)
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:89:15516
    at div
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:2869)
    at HeaderActionButtons (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:89:16716)
    at div
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at header
    at Header (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:89:17108)
    at div
    at IndexLayout (https://bolt.new/assets/_index-NyEmdF5V.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at Layout (https://bolt.new/assets/root-Dgim_hb8.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)

### Expected behavior

<img width="960" alt="image" src="https://github.com/user-attachments/assets/c7b8ebd4-3331-416a-9fbb-16b84886b9e0" />

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 134200108,
  "usedJSHeapSize": 108607152,
  "jsHeapSizeLimit": 2197815296
}
```

### Additional context

Error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at button
    at https://bolt.new/assets/login-CwjdxPzR.js:1:40172
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17807
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:4487
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17807
    at https://bolt.new/assets/login-CwjdxPzR.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:4487
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:38662
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:4734
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:2869)
    at https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:89:15516
    at div
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:49:2869)
    at HeaderActionButtons (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:89:16716)
    at div
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at header
    at Header (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:89:17108)
    at div
    at IndexLayout (https://bolt.new/assets/_index-NyEmdF5V.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at Layout (https://bolt.new/assets/root-Dgim_hb8.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
```

**Comment by AriPerkkio** [comment]
Hey @tandia00, thanks for the report.

Let's track this bug at #4530.
