### ISSUE TITLE
[plugin:vite:import-analysis] Failed to resolve import "./ProductCard" from "src/components/products/ProductGrid.tsx". Does the file exist?

### ISSUE THREAD

**Issue by YordanMitev** [stackblitz/bolt.new#4576]
### Describe the bug

/home/project/src/components/products/ProductGrid.tsx:3:28
15 |    window.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;
16 |  }
17 |  import { ProductCard } from "./ProductCard";
   |                               ^
18 |  import { filterProducts } from "../../utils/productUtils";
19 |  export function ProductGrid({ products, selectedCategory, onAddToCart }) {
    at TransformPluginContext._formatError (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49242:41)
    at TransformPluginContext.error (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49237:16)
    at normalizeUrl (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64033:23)
    at async eval (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64165:39)
    at async TransformPluginContext.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:64092:7)
    at async PluginContainer.transform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49083:18)
    at async loadAndTransform (file:///home/project/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:51916:27)
    at async viteTransformMiddleware (file:///home/project/node_modules/vite/dist/node/chunks/de

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-2aose9ny

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

I wrote the following:
add categories for the different type of items types

### Expected behavior

To add categories to the web sitewebsite

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 184617668,
  "usedJSHeapSize": 116476416,
  "jsHeapSizeLimit": 4294705152
}
Username = YordanMitev
Chat ID = e602fb355327
```

**Comment by codewithtyler** [comment]
Hi @YordanMitev,

Thanks for the report. This issue typically happens when you have a component (in your case ProductCard)  that's not properly exporting the component in the file. If you tell this to Bolt and give it the error you pasted into this report you should be able to resolve the issue in a prompt or two. I would have taken a look for you but you didn't make the app public despite marking that you did so trying to guide you in your next prompt is the best I can do at this time.
