### ISSUE TITLE
making same mistake again and again

### ISSUE THREAD

**Issue by ser-shivam** [stackblitz/bolt.new#4618]
### Describe the bug

Supabase API error, 400, Failed to run sql query: ERROR:  23505: duplicate key value violates unique constraint "schema_migrations_pkey"
DETAIL:  Key (version)=(0001) already exists.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-39mcmffu

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

not able to fix simple database

### Expected behavior

making same mistake again and again

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 117676148,
  "usedJSHeapSize": 68619576,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error:
```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at gi (https://bolt.new/assets/components-BPQqK2_k.js:24:34328)
    at ii (https://bolt.new/assets/components-BPQqK2_k.js:22:23466)
    at https://bolt.new/assets/_index-DRnYCE-h.js:130:1809
    at Qj (https://bolt.new/assets/components-BPQqK2_k.js:24:24613)
    at kk (https://bolt.new/assets/components-BPQqK2_k.js:24:32084)
    at ik (https://bolt.new/assets/components-BPQqK2_k.js:24:31931)
    at hk (https://bolt.new/assets/components-BPQqK2_k.js:24:31479)
    at Wk (https://bolt.new/assets/components-BPQqK2_k.js:24:41525)
    at Pk (https://bolt.new/assets/components-BPQqK2_k.js:24:40883)
    at Ek (https://bolt.new/assets/components-BPQqK2_k.js:24:37416)
Component stack: 
    at https://bolt.new/assets/_index-DRnYCE-h.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-DRnYCE-h.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DRnYCE-h.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:97:146)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at Layout (https://bolt.new/assets/root-Dgim_hb8.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at RenderErrorBoundary (https://bolt.new/assets/index-BkkrDsoJ.js:36:3227)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at RemixErrorBoundary (https://bolt.new/assets/components-BPQqK2_k.js:121:84)
    at RemixBrowser (https://bolt.new/assets/entry.client-Pqxp-6g8.js:19:1820)
```

**Comment by IbrahimElbouhissi** [comment]
The same here. I read many issues talking about the same problem which I also faced. After I reached to acceptable level of developing an AI powered tool, and after one change, I had lost all things and started again with a new database and new project. 15M of tokens  were wasted for nothing!

**Comment by ramshriramgit** [comment]
yeah same issue, they are deliberately letting it happen to eat our tokens. I have noticed this since long.

**Comment by AriPerkkio** [comment]
Hey @ser-shivam, thanks for the report.

Let's track this issue at #4924.
