### ISSUE TITLE
bug bolt ai

### ISSUE THREAD

**Issue by Akerahim** [stackblitz/bolt.new#4619]
### Describe the bug

voila ce que ca ecrit  : NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at div
    at div
    at MenuContent$1 (https://bolt.new/assets/_index-DRnYCE-h.js:88:124762)
    at div
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-DRnYCE-h.js:88:121342
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-DRnYCE-h.js:145:9492
    at https://bolt.new/assets/_index-DRnYCE-h.js:145:26365
    at Chat (https://bolt.new/assets/_index-DRnYCE-h.js:145:25147)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DRnYCE-h.js:145:39818)
    at Index$1
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at Layout (https://bolt.new/assets/root-Dgim_hb8.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)

### Link to the Bolt URL that caused the error

https://bolt.new/

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

<img width="919" alt="Capture d’écran 2024-12-24 à 01 07 39" src="https://github.com/user-attachments/assets/b99443a9-ef29-4e51-a5b6-24526bc3ad34" />

### Expected behavior

<img width="919" alt="Capture d’écran 2024-12-24 à 01 07 39" src="https://github.com/user-attachments/assets/e718278b-ea59-4dce-9150-0e7903782a11" />

### Screen Recording / Screenshot

https://bolt.new/

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58385646,
  "usedJSHeapSize": 57225066,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at div
    at div
    at MenuContent$1 (https://bolt.new/assets/_index-DRnYCE-h.js:88:124762)
    at div
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-DRnYCE-h.js:88:121342
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-DRnYCE-h.js:145:9492
    at https://bolt.new/assets/_index-DRnYCE-h.js:145:26365
    at Chat (https://bolt.new/assets/_index-DRnYCE-h.js:145:25147)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DRnYCE-h.js:145:39818)
    at Index$1
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-U3t4dt5d.js:1:1119)
    at Layout (https://bolt.new/assets/root-Dgim_hb8.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
```

**Comment by AriPerkkio** [comment]
Hey @Akerahim, thanks for the report.

Let's track this bug at #4565.
