### ISSUE TITLE
使用中报错

### ISSUE THREAD

**Issue by pared2021** [stackblitz/bolt.new#462]
### Describe the bug

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at to (https://bolt.new/assets/components-g8_Fbz61.js:24:25478)
    at je (https://bolt.new/assets/components-g8_Fbz61.js:24:30669)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27717)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xt6uzc

### Steps to reproduce

提出编写要求后出现：

### Expected behavior

正常使用

### Screen Recording / Screenshot

![1728699409834](https://github.com/user-attachments/assets/65650820-60dc-4992-bd57-e57e76e66f21)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by endocytosis** [comment]
Appreciate the feedback! We are aware of this issue and are tracking is here: #2556.

**Comment by pared2021** [comment]
补充一点，似乎和edge浏览器自带的翻译插件有关系，之前出现上述提示都是开启了自动翻译功能导致的

**Comment by endocytosis** [comment]
Great, thanks for the additional feedback!
