### ISSUE TITLE
Facebook hacking

### ISSUE THREAD

**Issue by MdSaimum** [stackblitz/bolt.new#4656]
### Describe the bug

Facebook hacking

### Link to the Bolt URL that caused the error

https://bolt.new/Facebookhacking/

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Facebook hacking

### Expected behavior

Facebook hacking

### Screen Recording / Screenshot

Facebook hacking

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36
performance.memory = {
  "totalJSHeapSize": 50400000,
  "usedJSHeapSize": 47400000,
  "jsHeapSizeLimit": 521000000
}
```

### Additional context

Error:
```
out-of-memory: RuntimeError: unreachable
    at https://w-credentialless-staticblitz.com/fs_bg.c8c182a3.wasm:wasm-function[954]:0x681a9
    at https://w-credentialless-staticblitz.com/fs_bg.c8c182a3.wasm:wasm-function[496]:0x5bb16
    at _0x2d403e (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/iframe.main.c8c182a3.js:1:413489)
    at _0x1797c8 (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/iframe.main.c8c182a3.js:1:413896)
    at async _0x6ea670.initFileSystem (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/iframe.main.c8c182a3.js:1:414445)
    at async _0x124c74.init (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/iframe.main.c8c182a3.js:4:38352)
```

**Comment by MdSaimum** [comment]
Facebook hacking Ai

**Comment by MdSaimum** [comment]
Facebook hacking
