### ISSUE TITLE
access deny with my account github

### ISSUE THREAD

**Issue by Pi846** [stackblitz/bolt.new#4671]
### Describe the bug

![image](https://github.com/user-attachments/assets/d8a08916-ac65-4e09-a7ab-f46b2fb11978)

### Link to the Bolt URL that caused the error

https://bolt.new/

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4c424881-6ace-433c-8220-e2ac3a780c6b)

### Expected behavior

![image](https://github.com/user-attachments/assets/1d6a175d-f334-4eb2-951d-244a4dd352c2)

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/0577580a-e059-44c0-a2be-254d87f49b5d)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 137146423,
  "usedJSHeapSize": 101804623,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at div
    at div
    at MenuContent$1 (https://bolt.new/assets/_index-BRmzy-5O.js:88:123609)
    at div
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-BRmzy-5O.js:88:120189
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:9492
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:26365
    at Chat (https://bolt.new/assets/_index-BRmzy-5O.js:145:25147)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BRmzy-5O.js:145:39818)
    at Index$1
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at Layout (https://bolt.new/assets/root-gA16Bm4s.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
```

**Comment by AriPerkkio** [comment]
Hey @Pi846, thanks for the report.

Let's track this bug at #4565.
