### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module: https://bolt.new/assets/ConsoleInspector-og6rhpFv.js

### ISSUE THREAD

**Issue by scooby1800s** [stackblitz/bolt.new#4673]
### Describe the bug

An unexpected error occured
Errors

TypeError: Failed to fetch dynamically imported module: https://bolt.new/assets/ConsoleInspector-og6rhpFv.js
Component stack: 
    at Lazy
    at div
    at summary
    at details
    at div
    at PreviewRenderer (https://bolt.new/assets/_index-BRmzy-5O.js:73:10691)
    at Suspense
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:41:25572)
    at div
    at Collapsible (https://bolt.new/assets/_index-BRmzy-5O.js:30:9487)
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:41:25572)
    at https://bolt.new/assets/_index-BRmzy-5O.js:30:11399
    at PotentialProblems (https://bolt.new/assets/_index-BRmzy-5O.js:88:1233)
    at div
    at https://bolt.new/assets/_index-BRmzy-5O.js:88:8395
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at div
    at div
    at div
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:97:146)
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:9492
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-BRmzy-5O.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BRmzy-5O.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:97:146)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at Layout (https://bolt.new/assets/root-gA16Bm4s.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at RenderErrorBoundary (https://bolt.new/assets/index-BkkrDsoJ.js:36:3227)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at RemixErrorBoundary (https://bolt.new/assets/components-BPQqK2_k.js:121:84)
    at RemixBrowser (https://bolt.new/assets/entry.client-Pqxp-6g8.js:19:1820)
Report an issue
Try again

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lk6ozqvr

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

ASK PROGRAM TO START, CLICK GAME FROM LANDING PAGE THEN ERROR

### Expected behavior

landing page to to link to game and open

### Screen Recording / Screenshot

.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
performance.memory = {
  "totalJSHeapSize": 111768230,
  "usedJSHeapSize": 99313598,
  "jsHeapSizeLimit": 2160066560
}
```

### Additional context

Error:
```
TypeError: Failed to fetch dynamically imported module: https://bolt.new/assets/ConsoleInspector-og6rhpFv.js
Component stack: 
    at Lazy
    at div
    at summary
    at details
    at div
    at PreviewRenderer (https://bolt.new/assets/_index-BRmzy-5O.js:73:10691)
    at Suspense
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:41:25572)
    at div
    at Collapsible (https://bolt.new/assets/_index-BRmzy-5O.js:30:9487)
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:41:25572)
    at https://bolt.new/assets/_index-BRmzy-5O.js:30:11399
    at PotentialProblems (https://bolt.new/assets/_index-BRmzy-5O.js:88:1233)
    at div
    at https://bolt.new/assets/_index-BRmzy-5O.js:88:8395
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at div
    at div
    at div
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:97:146)
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:9492
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-BRmzy-5O.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BRmzy-5O.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:97:146)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at Layout (https://bolt.new/assets/root-gA16Bm4s.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at RenderErrorBoundary (https://bolt.new/assets/index-BkkrDsoJ.js:36:3227)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at RemixErrorBoundary (https://bolt.new/assets/components-BPQqK2_k.js:121:84)
    at RemixBrowser (https://bolt.new/assets/entry.client-Pqxp-6g8.js:19:1820)
```

**Comment by AriPerkkio** [comment]
Hey @scooby1800s, thanks for the report.

Let's track this bug at #5022.
