### ISSUE TITLE
Erro ao pedir correção.

### ISSUE THREAD

**Issue by jerossinilp** [stackblitz/bolt.new#4684]
### Describe the bug

Esta consumindo meus tokens mas não esta funcionando.
Este é um exemplo de erro que estou enfentando diariamente.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gzymqo

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Só perdir uma correção e este erro ocorre.

### Expected behavior

Esperava que ele fizesse a correção no arquivo.

### Screen Recording / Screenshot

Não tenho gravação.

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 105695026,
  "usedJSHeapSize": 80375762,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at Yj (https://bolt.new/assets/components-BPQqK2_k.js:24:26194)
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:27278)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:31024)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at div
    at div
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at https://bolt.new/assets/_index-BRmzy-5O.js:88:23415
    at div
    at div
    at div
    at div
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:9492
    at https://bolt.new/assets/_index-BRmzy-5O.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-BRmzy-5O.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BRmzy-5O.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at Layout (https://bolt.new/assets/root-gA16Bm4s.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
```

**Comment by AriPerkkio** [comment]
Hey @jerossinilp, thanks for the report.

Let's track this bug at #5050.
