### ISSUE TITLE
schema migration version number renaming loop error

### ISSUE THREAD

**Issue by brasscats** [stackblitz/bolt.new#4727]
### Describe the bug

It gets stuck in a schema migration version number renaming loop where it doesn't check to see if the version number already exists in supabase.  

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-woendavy

### Validations

- [ ] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

Try multiple schema migrations and updates.

### Expected behavior

It's not supposed to rename a schema migration using a version number prefix that already exists.

Here is likely what needs to happen per chatgpt:
 
1. Identify the Root Cause
Bolt.new’s Migration Logic: Investigate how Bolt.new handles migrations. Check if it:

Reads the schema_migrations table before running migrations.
Ignores existing migration versions, leading to conflicts.
Supabase State: Confirm if the schema_migrations table in Supabase accurately reflects applied migrations.

2. Resolve Duplicate Key Issues for All Versions
To ensure no migration conflicts:

List all existing migrations in Supabase:

sql
Copy code
SELECT * FROM schema_migrations;
Compare this list to the migrations Bolt.new is trying to apply.
Remove conflicting versions if they are already applied correctly:

sql
DELETE FROM schema_migrations WHERE version IN ('0087', '0088', '0089', ...);
Replace '0087', '0088', '0089' with all problematic versions.

3. Implement Pre-Migration Validation in Bolt.new
To prevent repeated attempts to apply migrations:

Modify the migration scripts in Bolt.new to check for existing versions:

Add a conditional SQL block to each migration:

sql
Copy code
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = 'xxxx') THEN
    -- Migration logic here
  END IF;
END $$;

If Bolt.new supports hooks or callbacks:

Add a pre-migration hook to query the schema_migrations table.
Skip migrations if their version already exists.

4. Reset the Migration State (if appropriate)
If the migration system is too corrupted to fix manually, consider resetting the migration state:

Backup Your Database:

Export all current data to avoid accidental data loss.

Clear the schema_migrations Table:

sql
TRUNCATE schema_migrations;
Reapply All Migrations:

Re-run migrations from scratch:
supabase db push
Ensure all migrations are applied correctly.

5. Synchronize Bolt.new with Supabase
Ensure Bolt.new has a correct view of the applied migrations:

Review Bolt.new’s migration management files or metadata.
Manually update its internal migration state to match Supabase’s schema_migrations.
6. Improve Workflow for Future Migrations
Automated Pre-Check:

Integrate a step in your CI/CD pipeline to compare Bolt.new’s migration versions with Supabase before applying migrations.
Example: Write a script to query Supabase and compare with Bolt.new’s migration directory.
Logging:

Enable verbose logging in Bolt.new to debug migration issues in real time.
Schema Migration Tool:

Consider using a more robust schema migration tool (e.g., Flyway or Liquibase) alongside Bolt.new if its migration handling remains problematic.

Optional: Use a Migration Reset Script
To streamline the process, create a script that:

Fetches all applied migrations from Supabase.
Compares them with Bolt.new migrations.
Deletes duplicates or skips already-applied migrations.

Here’s a Python-based example:

import psycopg2

# Connect to your Supabase database
conn = psycopg2.connect("dbname=<db_name> user=<user> password=<password> host=<host>")
cur = conn.cursor()

# Fetch existing migrations
cur.execute("SELECT version FROM schema_migrations;")
existing_migrations = {row[0] for row in cur.fetchall()}

# Bolt.new migration versions (example list)
bolt_migrations = {"0087", "0088", "0089", ...}

# Find duplicates
duplicates = bolt_migrations.intersection(existing_migrations)

# Remove duplicates
for version in duplicates:
    cur.execute("DELETE FROM schema_migrations WHERE version = %s;", (version,))

conn.commit()
cur.close()
conn.close()
This ensures your database and Bolt.new stay in sync.

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/4bf348be-ce19-415b-9b1a-4a72434ff2de)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 97356474,
  "usedJSHeapSize": 93804506,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error:
```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at gi (https://bolt.new/assets/components-BPQqK2_k.js:24:34328)
    at ii (https://bolt.new/assets/components-BPQqK2_k.js:22:23466)
    at https://bolt.new/assets/_index-DfMadphr.js:130:1809
    at Qj (https://bolt.new/assets/components-BPQqK2_k.js:24:24613)
    at kk (https://bolt.new/assets/components-BPQqK2_k.js:24:32084)
    at ik (https://bolt.new/assets/components-BPQqK2_k.js:24:31931)
    at hk (https://bolt.new/assets/components-BPQqK2_k.js:24:31479)
    at Wk (https://bolt.new/assets/components-BPQqK2_k.js:24:41525)
    at Pk (https://bolt.new/assets/components-BPQqK2_k.js:24:40883)
    at Ek (https://bolt.new/assets/components-BPQqK2_k.js:24:37416)
Component stack: 
    at https://bolt.new/assets/_index-DfMadphr.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-DfMadphr.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DfMadphr.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:97:146)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DZTqEPLs.js:1:1119)
    at Layout (https://bolt.new/assets/root-gA16Bm4s.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at RenderErrorBoundary (https://bolt.new/assets/index-BkkrDsoJ.js:36:3227)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at RemixErrorBoundary (https://bolt.new/assets/components-BPQqK2_k.js:121:84)
    at RemixBrowser (https://bolt.new/assets/entry.client-Pqxp-6g8.js:19:1820)
```

**Comment by AriPerkkio** [comment]
Hey @brasscats, thanks for the report.

Let's track this issue at #4924.
