### ISSUE TITLE
He takes points without doing the right thing.

### ISSUE THREAD

**Issue by FAGEED00** [stackblitz/bolt.new#4738]
### Describe the bug

Despite the attempt to correct it, the error remains the same.
[plugin:vite:esbuild] Transform failed with 1 error:
/home/project/src/hooks/useAuth.ts:77:26: ERROR: Expected ">" but found "value"
/home/project/src/hooks/useAuth.ts:77:26
Expected ">" but found "value"
75 |  
76 |    return (
77 |      <AuthContext.Provider value={value}>
   |                            ^
78 |        {!loading && children}
79 |      </AuthContext.Provider>
    at failureErrorWithLog (/home/project/node_modules/esbuild/lib/main.js:1462:15)
    at eval (/home/project/node_modules/esbuild/lib/main.js:745:50)
    at responseCallbacks.<computed> (/home/project/node_modules/esbuild/lib/main.js:612:9)
    at handleIncomingPacket (/home/project/node_modules/esbuild/lib/main.js:667:12)
    at Socket.readFromStdout (/home/project/node_modules/esbuild/lib/main.js:590:7)
    at Socket.emit (node:events:30:10899)
    at addChunk (node:internal/streams/readable:225:3685)
    at readableAddChunk (node:internal/streams/readable:225:3393)
    at Readable.push (node:internal/streams/readable:225:4971)
    at _0x50b08f.onStreamRead (node:internal/stream_base_commons:211:2596

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-do26zhz6

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

I don't know

### Expected behavior

I don't know

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 80950897,
  "usedJSHeapSize": 62385781,
  "jsHeapSizeLimit": 4294705152
}
Username = FAGEED00
Chat ID = 2f94584b3a83
```

**Comment by aersosi** [comment]
Rename .js -> .jsx / .ts -> .tsx
