### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by AliveNata** [stackblitz/bolt.new#4799]
### Describe the bug

when I login at admin login page using admin@example.com, then show errors like this 

TypeError: Failed to fetch dynamically imported module: https://bolt.new/assets/ConsoleInspector-C6nmz1ex.js
Component stack: 
    at Lazy
    at div
    at summary
    at details
    at div
    at PreviewRenderer (https://bolt.new/assets/_index-DrWpiSAS.js:73:10691)
    at Suspense
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:41:25572)
    at div
    at Collapsible (https://bolt.new/assets/_index-DrWpiSAS.js:30:9487)
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:41:25572)
    at https://bolt.new/assets/_index-DrWpiSAS.js:30:11399
    at PotentialProblems (https://bolt.new/assets/_index-DrWpiSAS.js:88:1233)
    at div
    at https://bolt.new/assets/_index-DrWpiSAS.js:88:8395
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:1:1119)
    at div
    at div
    at div
    at div
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:97:146)
    at https://bolt.new/assets/_index-DrWpiSAS.js:145:9492
    at https://bolt.new/assets/_index-DrWpiSAS.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-DrWpiSAS.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DrWpiSAS.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:97:146)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:1:1119)
    at Layout (https://bolt.new/assets/root-BA1kdUmO.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at RenderErrorBoundary (https://bolt.new/assets/index-BkkrDsoJ.js:36:3227)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at RemixErrorBoundary (https://bolt.new/assets/components-BPQqK2_k.js:121:84)
    at RemixBrowser (https://bolt.new/assets/entry.client-Pqxp-6g8.js:19:1820)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-81ru5aqs

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

1. go to /admin/login
2. fill username and password
3. submit

### Expected behavior

I wish, i can access admin page

### Platform

```
Browser name = Chrome
Full version = 128.0.0.0
Major version = 128
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 OPR/114.0.0.0
performance.memory = {
  "totalJSHeapSize": 97518924,
  "usedJSHeapSize": 74075972,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

Error:
```
TypeError: Failed to fetch dynamically imported module: https://bolt.new/assets/ConsoleInspector-C6nmz1ex.js
Component stack: 
    at Lazy
    at div
    at summary
    at details
    at div
    at PreviewRenderer (https://bolt.new/assets/_index-DrWpiSAS.js:73:10691)
    at Suspense
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:41:25572)
    at div
    at Collapsible (https://bolt.new/assets/_index-DrWpiSAS.js:30:9487)
    at div
    at div
    at MotionComponent (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:41:25572)
    at https://bolt.new/assets/_index-DrWpiSAS.js:30:11399
    at PotentialProblems (https://bolt.new/assets/_index-DrWpiSAS.js:88:1233)
    at div
    at https://bolt.new/assets/_index-DrWpiSAS.js:88:8395
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:1:1119)
    at div
    at div
    at div
    at div
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:97:146)
    at https://bolt.new/assets/_index-DrWpiSAS.js:145:9492
    at https://bolt.new/assets/_index-DrWpiSAS.js:145:26365
    at ProjectImport (https://bolt.new/assets/_index-DrWpiSAS.js:145:25378)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-DrWpiSAS.js:145:39818)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ErrorBoundary (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:97:146)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-BEaXsMWi.js:1:1119)
    at Layout (https://bolt.new/assets/root-BA1kdUmO.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at RenderErrorBoundary (https://bolt.new/assets/index-BkkrDsoJ.js:36:3227)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at RemixErrorBoundary (https://bolt.new/assets/components-BPQqK2_k.js:121:84)
    at RemixBrowser (https://bolt.new/assets/entry.client-Pqxp-6g8.js:19:1820)
```

**Comment by AriPerkkio** [comment]
Hey @AliveNata, thanks for the report.

Let's track this bug at #5022.
