### ISSUE TITLE
port and ui not showing

### ISSUE THREAD

**Issue by djahlor** [stackblitz/bolt.new#48]
### Describe the bug

![CleanShot 2024-10-05 at 16 59 27@2x](https://github.com/user-attachments/assets/b074b52d-3300-4913-85f6-34818800b62b)
---

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-whizxq

### Steps to reproduce

hard to say tbh

### Expected behavior

port showing and loading

### Screen Recording / Screenshot

![CleanShot 2024-10-05 at 16 59 27@2x](https://github.com/user-attachments/assets/cd93c8ee-be04-4655-ad70-c88d571540db)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 152415315,
  "usedJSHeapSize": 129549083,
  "jsHeapSizeLimit": 4294705152
}
Username = djahlor
Chat ID = 508c7f307498
```

### Additional context

-

**Comment by Nemikolh** [comment]
Hey @djahlor! Thanks for opening this issue!

I'm wondering, when you open your project in stackblitz, (https://stackblitz.com/edit/sb1-whizxq), I'm seeing a couple of errors in the terminal:

```
[1] Server running on port 3000
[1] ValidationError: An undefined 'request.ip' was detected. This might indicate a misconfiguration or the connection being destroyed prematurely. See https://express-rate-limit.github.io/ERR_ERL_UNDEFINED_IP_ADDRESS/ for more information.
[1]     at ValidationError (file:///home/projects/sb1-whizxq/node_modules/express-rate-limit/dist/index.mjs:83:5)
[1]     at ip (file:///home/projects/sb1-whizxq/node_modules/express-rate-limit/dist/index.mjs:115:13)
[1]     at getValidations/wrappedValidations[name] (file:///home/projects/sb1-whizxq/node_modules/express-rate-limit/dist/index.mjs:351:22)
[1]     at keyGenerator (file:///home/projects/sb1-whizxq/node_modules/express-rate-limit/dist/index.mjs:604:20)
[1]     at rateLimit/middleware< (file:///home/projects/sb1-whizxq/node_modules/express-rate-limit/dist/index.mjs:659:32) {
[1]   code: 'ERR_ERL_UNDEFINED_IP_ADDRESS',
[1]   help: 'https://express-rate-limit.github.io/ERR_ERL_UNDEFINED_IP_ADDRESS/'
[1] }
[1] ENOENT: no such file or directory, stat '/home/projects/sb1-whizxq/dist/index.html'
```

Have you noticed those as well? 

Other than that do you think you could share errors you saw in your devtools?
