### ISSUE TITLE
Pathe

### ISSUE THREAD

**Issue by BIGPATHE667** [stackblitz/bolt.new#4829]
### Describe the bug

veux devenir un boss sur Shopify

### Link to the Bolt URL that caused the error

https://bolt.new/

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

quo

### Expected behavior

rien

### Screen Recording / Screenshot

autorizer

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 55024019,
  "usedJSHeapSize": 53906879,
  "jsHeapSizeLimit": 2197815296
}
```

### Additional context

Error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at div
    at div
    at MenuContent$1 (https://bolt.new/assets/_index-BevwFlxN.js:88:125317)
    at div
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-BevwFlxN.js:88:121897
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at div
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at https://bolt.new/assets/_index-BevwFlxN.js:145:9492
    at https://bolt.new/assets/_index-BevwFlxN.js:145:26364
    at Chat (https://bolt.new/assets/_index-BevwFlxN.js:145:25146)
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BevwFlxN.js:145:39817)
    at Index$1
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at Layout (https://bolt.new/assets/root-DsplWjk2.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
    at W (https://bolt.new/assets/components-BPQqK2_k.js:24:43638)
```

**Comment by BIGPATHE667** [comment]
merci

**Comment by AriPerkkio** [comment]
Hey @BIGPATHE667, thanks for the report.

Let's track this bug at #4565.
