### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by Rickos312** [stackblitz/bolt.new#4830]
### Describe the bug

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at button
    at https://bolt.new/assets/login-CPr4_EBW.js:1:40172
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38662
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:4734
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:15516
    at div
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at HeaderActionButtons (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:16716)
    at div
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at header
    at Header (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:17108)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BevwFlxN.js:145:39817)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at Layout (https://bolt.new/assets/root-DsplWjk2.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-zwscjybv

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at button
    at https://bolt.new/assets/login-CPr4_EBW.js:1:40172
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38662
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:4734
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:15516
    at div
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at HeaderActionButtons (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:16716)
    at div
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at header
    at Header (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:17108)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BevwFlxN.js:145:39817)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at Layout (https://bolt.new/assets/root-DsplWjk2.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)

### Expected behavior

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at button
    at https://bolt.new/assets/login-CPr4_EBW.js:1:40172
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38662
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:4734
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:15516
    at div
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at HeaderActionButtons (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:16716)
    at div
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at header
    at Header (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:17108)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BevwFlxN.js:145:39817)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at Layout (https://bolt.new/assets/root-DsplWjk2.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)

### Screen Recording / Screenshot

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at button
    at https://bolt.new/assets/login-CPr4_EBW.js:1:40172
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38662
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:4734
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:15516
    at div
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at HeaderActionButtons (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:16716)
    at div
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at header
    at Header (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:17108)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BevwFlxN.js:145:39817)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at Layout (https://bolt.new/assets/root-DsplWjk2.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72957395,
  "usedJSHeapSize": 69944839,
  "jsHeapSizeLimit": 2197815296
}
```

### Additional context

Error:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Zj (https://bolt.new/assets/components-BPQqK2_k.js:24:26518)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27829)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28297)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
    at dk (https://bolt.new/assets/components-BPQqK2_k.js:24:28102)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27978)
Component stack: 
    at button
    at https://bolt.new/assets/login-CPr4_EBW.js:1:40172
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17807
    at https://bolt.new/assets/login-CPr4_EBW.js:1:17424
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:4487
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38662
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:4734
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:15516
    at div
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at Popper (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:38464)
    at Tooltip (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:3533)
    at Provider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:2697)
    at TooltipProvider (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:49:2869)
    at HeaderActionButtons (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:16716)
    at div
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at header
    at Header (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:89:17108)
    at div
    at IndexLayout (https://bolt.new/assets/_index-BevwFlxN.js:145:39817)
    at Index
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at Outlet (https://bolt.new/assets/index-BkkrDsoJ.js:36:7773)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at App
    at ClientOnly (https://bolt.new/assets/ErrorBoundary-DBztZbkn.js:1:1119)
    at Layout (https://bolt.new/assets/root-DsplWjk2.js:60:25)
    at RenderedRoute (https://bolt.new/assets/index-BkkrDsoJ.js:36:3987)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at DataRoutes (https://bolt.new/assets/components-BPQqK2_k.js:33:6470)
    at Router (https://bolt.new/assets/index-BkkrDsoJ.js:36:7825)
    at RouterProvider (https://bolt.new/assets/components-BPQqK2_k.js:33:3672)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
    at ck (https://bolt.new/assets/components-BPQqK2_k.js:24:27920)
```
<img width="165" alt="Capture d’écran 2024-12-30 à 14 34 26" src="https://github.com/user-attachments/assets/1feab77d-be7b-4d84-91d5-6044c8ace809" />

**Comment by AriPerkkio** [comment]
Hey @Rickos312, thanks for the report.

Let's track this bug at #4530.
