### ISSUE TITLE
Probleme de fond blanc dans mon projet

### ISSUE THREAD

**Issue by honorenduku** [stackblitz/bolt.new#4843]
### Describe the bug

Mon projet web ne s’affiche plus depuis un certain temps. J’ai tenté de résoudre ce problème, mais sans succès, et je ne comprends pas pourquoi l’écran reste blanc. J’ai également essayé d’utiliser la fonction "Undo" pour revenir en arrière, mais cela n’a pas résolu le problème.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-dg1xnzyx

### Validations

- [X] Please make your project public or accessible by URL. This will allow anyone trying to help you to easily reproduce the issue and provide assistance.

### Steps to reproduce

il suffit juste de lancer le projet et rien ne va s'afficher mais aprés avoir actualisé.

### Expected behavior

Je veux une solution à mon probleme et une brieve explication par rapport à ce sujet .

### Screen Recording / Screenshot

![Capture d’écran 2024-12-30 à 22 35 48](https://github.com/user-attachments/assets/86e85a22-a8d6-46e2-8d79-a7ec2096ccc5)

### Platform

```
Browser name = Chrome
Full version = 116.0.0.0
Major version = 116
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 70858016,
  "usedJSHeapSize": 69010880,
  "jsHeapSizeLimit": 2172649472
}
Username = honorenduku
Chat ID = 63457ea1b073
```

### Additional context

rien d'autre.

**Comment by honorenduku** [comment]
l'aide de toute personne m'ai précieuse. Merci d'avance.

**Comment by demangejeremy** [comment]
Ce n'est pas un problème lié à Bolt mais à votre projet.
Il faut ouvrir la console depuis le navigateur (inspecter) pour y lire ces erreurs : 

```
Invalid Supabase configuration: ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "VITE_SUPABASE_URL"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "VITE_SUPABASE_ANON_KEY"
    ],
    "message": "Required"
  }
]
    at get error (zod.js?v=827c9139:512:23)
    at _ZodObject.parse (zod.js?v=827c9139:588:18)
    at validateSupabaseConfig (config.ts:15:22)
    at client.ts:5:16
console.error @ .localservice@runtime.7f809d15.js:26
config.ts:18 Uncaught Error: Missing or invalid Supabase environment variables
    at validateSupabaseConfig (config.ts:18:11)
    at client.ts:5:16
```

Le message indique que des variables (VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY) doivent être mises dans un fichier .env.
