### ISSUE TITLE
5m token gone just with errors 

### ISSUE THREAD

**Issue by YDX64** [stackblitz/bolt.new#503]
### Describe the bug

 info Using wasm build of next-swc
- warn Attempted to load @next/swc-linux-x64-gnu, but an error occurred: Cannot load native addon because loading addons is disabled: /home/project/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node
- warn Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
- warn Attempted to load @next/swc-linux-x64-musl, but an error occurred: Cannot load native addon because loading addons is disabled: /home/project/node_modules/@next/swc-linux-x64-musl/next-swc.linux-x64-musl.node
- info Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/home/project/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!/home/project/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!/home/project/src/app/globals.css': No serializer registered for PostCSSSyntaxError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> PostCSSSyntaxError
Failed to compile.

./src/app/globals.css:1:1
Syntax error: /home/project/src/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;

./src/app/globals.css
Syntax error: /home/project/src/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. (1:1)

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;

    at new WebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:488214)
    at new HookWebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:307902)
    at tryRunOrWebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:308539)
    at __webpack_require_module__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130357)
    at __nested_webpack_require_153265__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:129784)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130649)
    at symbolIterator (/home/project/node_modules/next/dist/compiled/neo-async/async.js:1:14519)
    at done (/home/project/node_modules/next/dist/compiled/neo-async/async.js:1:14899)
    at Hook.eval (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:1441309)
    at Hook.CALL_ASYNC_DELEGATE (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:13:25925)
-- inner error --
Syntax error: /home/project/src/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. (1:1)

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;

    at Object.eval (/home/project/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!/home/project/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!/home/project/src/app/globals.css:2:7)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:901184)
    at Hook.eval (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:1441309)
    at Hook.CALL_DELEGATE (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:13:25819)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130390)
    at tryRunOrWebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:308493)
    at __webpack_require_module__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130357)
    at __nested_webpack_require_153265__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:129784)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130649)
    at symbolIterator (/home/project/node_modules/next/dist/compiled/neo-async/async.js:1:14519)

Generated code for /home/project/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!/home/project/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!/home/project/src/app/globals.css

Import trace for requested module:
./src/app/globals.css

> Build failed because of webpack errors
- info Creating an optimized production build .
~/project 16s
❯ npm start

> live-match-data-scraper@0.1.0 start
> next start

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /home/project/.env
Error: Could not find a production build in the '/home/project/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/home/project/node_modules/next/dist/server/next-server.js:345:23)
    at new Server (/home/project/node_modules/next/dist/server/base-server.js:151:29)
    at new NextNodeServer (/home/project/node_modules/next/dist/server/next-server.js:172:9)
    at NextServer.createServer (/home/project/node_modules/next/dist/server/next.js:179:24)
    at async eval (/home/project/node_modules/next/dist/server/next.js:200:31)
    at async NextServer.prepare (/home/project/node_modules/next/dist/server/next.js:160:24)
    at async Server.eval (/home/project/node_modules/next/dist/server/lib/render-server.js:123:17) {
  type: 'Error'
}

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-gyvg3q

### Steps to reproduce

 info Using wasm build of next-swc
- warn Attempted to load @next/swc-linux-x64-gnu, but an error occurred: Cannot load native addon because loading addons is disabled: /home/project/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node
- warn Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
- warn Attempted to load @next/swc-linux-x64-musl, but an error occurred: Cannot load native addon because loading addons is disabled: /home/project/node_modules/@next/swc-linux-x64-musl/next-swc.linux-x64-musl.node
- info Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/home/project/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!/home/project/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!/home/project/src/app/globals.css': No serializer registered for PostCSSSyntaxError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> PostCSSSyntaxError
Failed to compile.

./src/app/globals.css:1:1
Syntax error: /home/project/src/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;

./src/app/globals.css
Syntax error: /home/project/src/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. (1:1)

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;

    at new WebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:488214)
    at new HookWebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:307902)
    at tryRunOrWebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:308539)
    at __webpack_require_module__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130357)
    at __nested_webpack_require_153265__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:129784)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130649)
    at symbolIterator (/home/project/node_modules/next/dist/compiled/neo-async/async.js:1:14519)
    at done (/home/project/node_modules/next/dist/compiled/neo-async/async.js:1:14899)
    at Hook.eval (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:1441309)
    at Hook.CALL_ASYNC_DELEGATE (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:13:25925)
-- inner error --
Syntax error: /home/project/src/app/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. (1:1)

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;

    at Object.eval (/home/project/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!/home/project/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!/home/project/src/app/globals.css:2:7)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:901184)
    at Hook.eval (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:1441309)
    at Hook.CALL_DELEGATE (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:13:25819)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130390)
    at tryRunOrWebpackError (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:308493)
    at __webpack_require_module__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130357)
    at __nested_webpack_require_153265__ (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:129784)
    at eval (/home/project/node_modules/next/dist/compiled/webpack/bundle5.js:28:130649)
    at symbolIterator (/home/project/node_modules/next/dist/compiled/neo-async/async.js:1:14519)

Generated code for /home/project/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!/home/project/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!/home/project/src/app/globals.css

Import trace for requested module:
./src/app/globals.css

> Build failed because of webpack errors
- info Creating an optimized production build .
~/project 16s
❯ npm start

> live-match-data-scraper@0.1.0 start
> next start

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /home/project/.env
Error: Could not find a production build in the '/home/project/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/home/project/node_modules/next/dist/server/next-server.js:345:23)
    at new Server (/home/project/node_modules/next/dist/server/base-server.js:151:29)
    at new NextNodeServer (/home/project/node_modules/next/dist/server/next-server.js:172:9)
    at NextServer.createServer (/home/project/node_modules/next/dist/server/next.js:179:24)
    at async eval (/home/project/node_modules/next/dist/server/next.js:200:31)
    at async NextServer.prepare (/home/project/node_modules/next/dist/server/next.js:160:24)
    at async Server.eval (/home/project/node_modules/next/dist/server/lib/render-server.js:123:17) {
  type: 'Error'
}

### Expected behavior

working without any issue

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 172359072,
  "usedJSHeapSize": 149802404,
  "jsHeapSizeLimit": 4294705152
}
Username = YDX64
Chat ID = f5a93876583d
```

**Comment by kc0tlh** [comment]
@YDX64 please review issue #678 for tips on being more efficient with token usage
