### ISSUE TITLE
Bolt.New is not working

### ISSUE THREAD

**Issue by Mittrandill** [stackblitz/bolt.new#519]
### Describe the bug

I get this error when trying to create my project with bolt new.

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fe (https://bolt.new/assets/components-g8_Fbz61.js:24:33638)
    at np (https://bolt.new/assets/components-g8_Fbz61.js:22:22233)
    at pB (https://bolt.new/assets/_index-Ce_au2kK.js:3:631)
    at https://bolt.new/assets/_index-Ce_au2kK.js:3:700
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-Ce_au2kK.js:3:689
    at pB (https://bolt.new/assets/_index-Ce_au2kK.js:3:631)
    at https://bolt.new/assets/_index-Ce_au2kK.js:3:700
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-Ce_au2kK.js:3:689

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-njdcl2

### Steps to reproduce

I try open project with bolt.new and i see Application Error Page

### Expected behavior

My project is supposed to open properly with bolt new because it works when I open it with StackBlitz!

### Screen Recording / Screenshot

![Ekran görüntüsü 2024-10-13 151606](https://github.com/user-attachments/assets/7614aa10-c5e9-4119-b634-4b75976cdc10)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by 7heD3D1** [comment]
Same here. Any fixes?

**Comment by benzionsville** [comment]
Same for me today 11.11.2024

**Comment by Mohamed-Fleifel** [comment]
i got his:
TypeError: t.toSorted is not a function
    at Poe (https://bolt.new/assets/_index-xvs-ojK0.js:160:40134)
    at Fae (https://bolt.new/assets/_index-xvs-ojK0.js:160:95002)
    at Vo (https://bolt.new/assets/components-B64jh5hJ.js:22:16948)
    at Tc (https://bolt.new/assets/components-B64jh5hJ.js:24:43699)
    at Rc (https://bolt.new/assets/components-B64jh5hJ.js:24:39500)
    at Ep (https://bolt.new/assets/components-B64jh5hJ.js:24:39431)
    at dl (https://bolt.new/assets/components-B64jh5hJ.js:24:39289)
    at oo (https://bolt.new/assets/components-B64jh5hJ.js:24:35706)
    at ma (https://bolt.new/assets/components-B64jh5hJ.js:24:36507)
    at St (https://bolt.new/assets/components-B64jh5hJ.js:22:3258)
