### ISSUE TITLE
没有保存项目

### ISSUE THREAD

**Issue by Againster56** [stackblitz/bolt.new#624]
每次重新进入项目，项目内容都被清空的感觉，预览什么都没有

**Comment by benspak** [comment]
This has been a common issue. I'm hoping the team is working on patching it soon.

**Comment by Againster56** [comment]
经常出这个错误：Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at yc (https://bolt.new/assets/components-g8_Fbz61.js:24:25974)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27253)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)
    at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514)
    at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

**Comment by leon4u** [comment]
礼貌请问大家怎么解决这个问题的？每次进入都得重头来，这受不了诶。。

**Comment by AriPerkkio** [comment]
> 经常出这个错误：Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. at yc (https://bolt.new/assets/components-g8_Fbz61.js:24:25974) at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27253) at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709) at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401) at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709) at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401) at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27709) at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401) at gc (https://bolt.new/assets/components-g8_Fbz61.js:24:27514) at Ne (https://bolt.new/assets/components-g8_Fbz61.js:24:27401)

Hey @Againster56, thanks for the report!

This issue is tracked on https://github.com/stackblitz/bolt.new/issues/2556.
