### ISSUE TITLE
Repeating errors, Refreshed page, lost all progress + conversation gone.

### ISSUE THREAD

**Issue by ateeples** [stackblitz/bolt.new#652]
### Describe the bug

I've been creating a full stack application using bolt.new for a few days, and spent 36m tokens.  Yesterday I had spent 25m, deployed to github (as a backup), and then upgraded my plan to get more tokens to continue adding more features. 
I then used over 14m tokens to add new features, and ran into a looping problem that I was trying to troubleshoot using bolt.new.  I didn't redeploy because it wasn't working correctly.
Eventually the chat kept giving me errors and I was unable to send messages, so I refreshed the page. The page refreshed with an error, and this is what it said: (thank god I copied it before trying to go back, i hope this helps) : 

Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fe (https://bolt.new/assets/components-g8_Fbz61.js:24:33638)
    at np (https://bolt.new/assets/components-g8_Fbz61.js:22:22233)
    at vB (https://bolt.new/assets/_index-BVj7CPQ3.js:3:1036)
    at https://bolt.new/assets/_index-BVj7CPQ3.js:3:1105
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BVj7CPQ3.js:3:1094
    at vB (https://bolt.new/assets/_index-BVj7CPQ3.js:3:1036)
    at https://bolt.new/assets/_index-BVj7CPQ3.js:3:1105
    at Array.forEach (<anonymous>)
    at https://bolt.new/assets/_index-BVj7CPQ3.js:3:1094
    
    Now my conversation with bolt.new is completely gone. So I've essentially wasted 14m+ tokens trying to get the new features to work and lost any progress (if you can call it that) of adding the new features. 
    I'm going to try to reopen the app in stackblitz from my github repo and then try to reopen in bolt.new (if this is possible? idk), but this feels pretty not cool.
    
    ***EDIT: thankfully my browser saved the url and I listed it below. It still does not show up in my conversations though, and it looks like the progress has not been lost.  however, spending 14m tokens to add a new feature still feels pretty not cool.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-v9gnqq

### Steps to reproduce

this was the prompt I gave it. 
currently the app you've been building for me is not loading/rendering.  most recently we were working on adding a 'daily design warmup' feature where the users are all given the same prompt (it'll be a new prompt each day, recycling every 45 days or whatever makes sense), creates a design based on the prompt, and submits it.  The submitted designs would be shown in a gallery view where all users can 'upvote/like' submissions (they are shown anonymously), and upvotes/likes are tied to points.  for example, if a user gets 5 likes/upvotes today on their submission, and 10 tomorrow, they would have 15 points total.  We were also working on implementing a leaderboard, that would show the user's username and their total points. 
Please implement the required changes for me by always writing the full code in the code editor (DO NOT USE COMMENTS/PLACEHOLDERS) and restore the placeholders with actual code.  while maintaining existing functionality of all other pages/components/elements/etc. Adhere to the established minimalist light mode style guide. Let me know if any Supabase updates are needed.

### Expected behavior

I would expect it to attempt to resolve problems options to fix it. 

### Platform

- OS: macOS
- Browser: Chrome
My OS and browser are both up to date/ most recent versions.

**Comment by ateeples** [comment]
looks like it's happening again after I tried inspecting within the webcontainer and clearing the site data (which it told me to do to try to fix the issue of the app not rendering / showing a blank screen).  Maybe I'm accidentally clearing the cache/ site data from bolt.new instead of my app? 
I was inspecting the web app and copying/pasting the console messages into the chat when this happened. 
![bolt_new-errrors](https://github.com/user-attachments/assets/2dbfa36b-152d-4344-93d0-d306823046aa)

**Comment by kc0tlh** [comment]
Apologies for the frustrating experience during this beta period! 

Very glad to hear that your progress was not lost. I will link two issues that we are using to track our progress on token efficiency (issue #678) and chat conversation persistence (issue #39) that I think you will find relevant for updates. 

Best of luck with your project.

**Comment by psbailey31** [comment]
Same, tried to build an app, and it couldn't get a single page working before running out of daily tokens
