### ISSUE TITLE
article website with md files for articles

### ISSUE THREAD

**Issue by ireaneus** [stackblitz/bolt.new#69]
### Describe the bug

Cannot find package 'react' imported from /home/project/node_modules/swiper/swiper-react.mjs

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'react' imported from /home/project/node_modules/swiper/swiper-react.mjs
    at __node_internal_captureLargerStackTrace2 (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)
    at new NodeError (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:4149)
    at packageResolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:9724)
    at moduleResolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:10188)
    at defaultResolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:12372)
    at ModuleLoader.defaultResolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:3284)
    at ModuleLoader.resolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:2989)
    at ModuleLoader.getModuleJob (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:1938)
    at https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1047
    at _0x24d9dc.link (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:786141)
    at https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1002

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-haj7kx

### Steps to reproduce

asked to create a website for articles in markdown with a carousel banner

terminal:
~/project
❯ npm install && npm run dev

added 339 packages in 39s

154 packages are looking for funding
  run `npm fund` for details

> article-website@0.0.1 dev
> astro dev

13:26:39 [types] Generated 15ms

 astro  v4.15.11 ready in 524 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

13:26:39 watching for file changes...
13:26:47 [ERROR] Cannot find package 'react' imported from /home/project/node_modules/swiper/swiper-react.mjs
  Stack trace:
    at __node_internal_captureLargerStackTrace2 (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)
    at packageResolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:9724)
    at defaultResolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:12372)
    at ModuleLoader.resolve (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:2989)
    at https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1047
    at https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1002
^C

~/project 4m 9s
❯ 

### Expected behavior

It was to display 3 .md articles and a banner

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 58565542,
  "usedJSHeapSize": 55558894,
  "jsHeapSizeLimit": 2172649472
}
Username = ireaneus
Chat ID = 93b7e7d6a8ac
```

**Comment by Nemikolh** [comment]
Hey @ireaneus! Thanks for the report!

Looks like Bolt didn't add the [React integration](https://docs.astro.build/en/guides/integrations-guide/react/) to your `astro.config.mjs` file. 

It sometimes makes mistake like this! You can prompt it to fix the error by adding the react integration or add it yourself via the terminal and editor.

Let us know if you run into other issues!
