### ISSUE TITLE
Error when trying to run a dev build 

### ISSUE THREAD

**Issue by krazor94** [stackblitz/bolt.new#75]
### Describe the bug

*** Received structured exception #0xc0000005: access violation; stack: 7ffbe115301f 7ff6aba9337b 7ff6aba93443 7ff6aba874bc 7ff6aba87467 7ff6ab307d5e 7ff6ab30806f 7ff6aa1f1706 7ff6aa1f14ea 7ff6ab47f97f 7ff6ab486b36 7ff6ab47fe9c 7ff6ab486b36 7ff6ab47d80c 7ff6aa1e1551 7ff6acb68bff 7ffc007d257c 7ffc015eaf07
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (C:\Projects\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (C:\Projects\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:3521:16)   
    at async #waitForReady (C:\Projects\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9235:5)    
    at async Miniflare2._getProxyClient (C:\Projects\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9359:5)
    at async Miniflare2.getBindings (C:\Projects\bolt.new\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9378:25)
    at async getPlatformProxy (C:\Projects\bolt.new\node_modules\.pnpm\wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0\node_modules\wrangler\wrangler-dist\cli.js:210522:20)
    at async configureServer (C:\Projects\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///C:/Projects/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (C:\Projects\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:750:27)
    at async Promise.all (index 4)
    at async Module.resolveConfig (file:///C:/Projects/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async Object.resolveViteConfig (C:\Projects\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:71:20)
    at async build (C:\Projects\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\build.js:192:20)
    at async Object.viteBuild (C:\Projects\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\commands.js:183:5)
    at async Object.run (C:\Projects\bolt.new\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\run.js:252:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

https://github.com/stackblitz/bolt.new

### Steps to reproduce

Follow installation instructions and run pnmp run dev command

### Expected behavior

Run the dev build

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Photize** [comment]
unfortunately pnpm did the same error although i am on  a fork any updates yet

**Comment by gaoshengqing21** [comment]
@krazor94  Have you resolved this issue on Windows?

**Comment by Photize** [comment]
No currently gave up, there is a free version online that is useable if
needed

**Comment by gaoshengqing21** [comment]
@Photize Hello, is there a link

**Comment by Photize** [comment]
https://bolt.myaibuilt.app/

And his YT https://youtu.be/Cn2MRL_ZUOE?si=Xo3NZyJv2JkmfqYe

**Comment by codewithtyler** [comment]
Odd I haven't had any issues running Bolt on Windows with `pnpm run dev`

**Comment by akkayaberkin** [comment]
Download this 
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
and restart pc 
its work for me!

**Comment by Photize** [comment]
> use npm install Download this https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version and restart pc its work for me!

Great Thanks , I havent tested yet but the front end appears even on the Pinokio version whach also was failing :-)  so now you can install Pinkio from a windows installer and bolt.ne the multi llm version with 1 click and then start great many thx
