### ISSUE TITLE
Bolt's UI gets destroyed by React exception

### ISSUE THREAD

**Issue by sulco** [stackblitz/bolt.new#787]
### Describe the bug

Upon visiting a project, instead of seeing bolt, I'm getting the error message:

```
Application Error
Error: Invariance failed
    at qt (https://bolt.new/assets/_index-Cp7sBn6O.js:40:30031)
    at https://bolt.new/assets/_index-Cp7sBn6O.js:190:4030
    at Object.tc [as useMemo] (https://bolt.new/assets/components-B64jh5hJ.js:22:21277)
    at O.useMemo (https://bolt.new/assets/index-fw5NnR3n.js:9:6182)
    at fme (https://bolt.new/assets/_index-Cp7sBn6O.js:190:3258)
    at https://bolt.new/assets/_index-Cp7sBn6O.js:199:1675
    at Vo (https://bolt.new/assets/components-B64jh5hJ.js:22:16948)
    at Ji (https://bolt.new/assets/components-B64jh5hJ.js:24:3134)
    at cc (https://bolt.new/assets/components-B64jh5hJ.js:24:2350)
    at Tc (https://bolt.new/assets/components-B64jh5hJ.js:24:47013)
    
```

<img width="803" alt="image" src="https://github.com/user-attachments/assets/17105096-56ce-4751-88d8-c3b260aade40">

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-5txgkh

### Steps to reproduce

1. Go to https://bolt.new/~/sb1-5txgkh as not an owner (I've tried it in incognito and in another browser)
2. See the bolt's UI being replated by an error

### Expected behavior

Ideally, no error. As a project owner I'm not even seeing this. 

But if an error has to appear, make it not destroy the bolt's UI.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 72286056,
  "usedJSHeapSize": 68428520,
  "jsHeapSizeLimit": 4294705152
}
Username = sulco
Chat ID = 87049c87198c
```

**Comment by AriPerkkio** [comment]
This bug seems to be fixed now.
