### ISSUE TITLE
pnpm run dev ERROR

### ISSUE THREAD

**Issue by sambazhu** [stackblitz/bolt.new#807]
### Describe the bug

> bolt@ dev /data/bolt.new2/bolt.new
> remix vite:dev

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:953:11)
    at Socket._write (node:net:965:8)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at Runtime.updateConfig (/data/bolt.new2/bolt.new/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:5051:26)
    at async #assembleAndUpdateConfig (/data/bolt.new2/bolt.new/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9171:30)
    at async Mutex.runWith (/data/bolt.new2/bolt.new/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:3521:16)
    at async #waitForReady (/data/bolt.new2/bolt.new/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9235:5)
    at async Miniflare2._getProxyClient (/data/bolt.new2/bolt.new/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9359:5)
    at async Miniflare2.getBindings (/data/bolt.new2/bolt.new/node_modules/.pnpm/miniflare@3.20240701.0/node_modules/miniflare/dist/src/index.js:9378:25)
    at async getPlatformProxy (/data/bolt.new2/bolt.new/node_modules/.pnpm/wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0/node_modules/wrangler/wrangler-dist/cli.js:210522:20)
    at async configureServer (/data/bolt.new2/bolt.new/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///data/bolt.new2/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (/data/bolt.new2/bolt.new/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/plugin.js:750:27)
    at async Promise.all (index 3)
    at async resolveConfig (file:///data/bolt.new2/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async _createServer (file:///data/bolt.new2/bolt.new/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62977:18)
    at async dev (/data/bolt.new2/bolt.new/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/dev.js:39:16)
    at async Object.viteDev (/data/bolt.new2/bolt.new/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/cli/commands.js:220:3)
    at async Object.run (/data/bolt.new2/bolt.new/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/cli/run.js:271:7) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

https://github.com/stackblitz/bolt.new/blob/main/CONTRIBUTING.md

### Steps to reproduce

pnpm run dev

### Expected behavior

server start

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
For assistance with programming help on specific projects, please check out the discord: discord.gg/stackblitz
