### ISSUE TITLE
No hay manera de tener una continuidad, con tanto error

### ISSUE THREAD

**Issue by dano241** [stackblitz/bolt.new#819]
### Describe the bug

tres de cada 5 veces que ejecutas una consulta de chat y empieza a escribir código, se cuelga y da error, no tiene que ser con una secuencia o pregunta concreta, lo hace muy a menudo con cualquier cosa. Tampoco hay manera de gestionar una base de datos con prisma. Me hubiera gustado seguir pero he cancelado la susctipción has ta que se solucione, una lástima, me gusta
![8989](https://github.com/user-attachments/assets/2c2d0ab2-5075-4977-af15-7a007dab958d)

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-nextjs-shadcn-1lbhc1

### Steps to reproduce

Error: You cannot use different slug names for the same dynamic path ('deviceTypeId' !== 'brandId').
    at handleSlug (/home/project/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:94:31)
    at UrlNode._insert (/home/project/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:131:17)
    at UrlNode._insert (/home/project/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:142:40)
    at UrlNode._insert (/home/project/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:142:40)
    at UrlNode.insert (/home/project/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:13:14)
    at eval (/home/project/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:165:46)
    at getSortedRoutes (/home/project/node_modules/next/dist/shared/lib/router/utils/sorted-routes.js:165:21)
    at Watchpack.eval (/home/project/node_modules/next/dist/server/lib/router-utils/setup-dev.js:1332:65)

### Expected behavior

corregir los errores

### Screen Recording / Screenshot

![8989](https://github.com/user-attachments/assets/2287cc24-0e0d-4126-8b5c-3d1933c67322)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 178581404,
  "usedJSHeapSize": 144927716,
  "jsHeapSizeLimit": 4294705152
}
Username = Dano2412
Chat ID = d11c4ea738a6
```

**Comment by AriPerkkio** [comment]
Hey @dano241, thanks for the report!

This issue is tracked on #2556.
