### ISSUE TITLE
The AI cannot follow instructions and does not hold a proper memory

### ISSUE THREAD

**Issue by duhlink** [stackblitz/bolt.new#877]
https://bolt.new/~/sb1-cwzzbv

this is my chat

you can see that the AI has been making no progress for the last 15,000 tokens.

It will not follow instructions and continues to repeat previous mistakes, ignoring what we have discussed. 

There is a serious flaw in the memory feature and it's not possible to build a great solution when the AI cannot understand the context of the project. I do not have this same issue in Cursor and this is very frustrating as this is more expensive for an inferior product that has wasted my time up to this point.

I provided the AI with an entire solution and wanted it converted in to node.js or whatever it was good at... prompted like 50 times for it to log the code changes and error messages so I could provide them in the chat. I asked it to pay attention and avoid it's repeated mistakes and omissions/oversights as it rewrote code in an attempt to "fix" issues... recreating or creating new issues. 

Error:   Failed to scan for dependencies from entries:
  /home/project/index.html
/home/project/src/dashboard/index.html

  ✘ [ERROR] No matching export in "src/dashboard/services/api.js" for import "fetchErrors"

    src/dashboard/components/ErrorLog.jsx:3:9:
      3 │ import { fetchErrors } from '../services/api';
        ╵          ~~~~~~~~~~~

    at failureErrorWithLog (/home/project/node_modules/esbuild/lib/main.js:1462:15)
    at eval (/home/project/node_modules/esbuild/lib/main.js:935:25)
    at runOnEndCallbacks (/home/project/node_modules/esbuild/lib/main.js:1305:45)
    at buildResponseToResult (/home/project/node_modules/esbuild/lib/main.js:933:7)
    at eval (/home/project/node_modules/esbuild/lib/main.js:945:9)
    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-4nj5l1tf.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:21460)
    at new Promise (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-4nj5l1tf.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:21431)
    at requestCallbacks.on-end (/home/project/node_modules/esbuild/lib/main.js:944:54)
    at handleRequest (/home/project/node_modules/esbuild/lib/main.js:637:17)

this are mistakes that the AI shouldn't be making... the npm logs are being written to a directory that is hidden and when accessed, it does not include the log file displayed in the terminal... ????

I had a button that was intended to do the following:

****
Add this functionality - this is the goal, we are not there yet, approach this systematically:

 on click, "Test Connection" create a code snapshot AND compare the code snapshot to the previous run, ie: 00000, it will create a file called 00001_current_code.txt for the code snapshot and create an additional file 00001_code_changes_and_log.txt (or .csv or .log, if line numbers will help for debugging, include them) -this will list the changes in the code from the previous version and include the log from the current run.

on click, "Test Connection", a log of what happened on the run needs to be saved to 00001_run_summary that includes the data needed to debug, successful actions and errors, data in JSON format or the terminal message on errors only to provide information for debugging. 

Add a button to display 00001_code_changes_and_log to the UI, if possible, also have it copy the data to my clipboard so I can paste it. The button will be called "Display Code Changes and Log", on click display 00001_code_changes and 00001_run_summary in a combined format with proper context labels, this needs to be clear and concise. Save this to a file called 00001_run_analysis as well. 

The goal is to be able to provide bolt.new with the most information to be able to proficiently update the code. At the top of the file 00001_run_analysis I want to include a prompt that explains what the data is, what the intention was and what the result was, then a prompt to make calculated and precision updates to the code to debug without omitting any of the previous code or reverting code to previously attempted code changes that we've already proven that did not provide the intended outcome. 
****

It added the button but kept breaking things when trying to fix errors, omitting things and even removed the button entirely with all it's features we'd been working on while trying to bug fix... like serious WTF 

I honestly want a refund, almost 20 million tokens and I am no further than I was when I provided my existing code on my first prompt, things have become worse and for some reason the AI cannot understand API REST protocol or if it does, it cannot do it in node.js properly. The JSON it provides has like URL: /sample/test/ when it has been provided with the URL, it removes Authorization: Basic ***** and does not replace ***** with the login:password in base64 as instructed. While trying to bug fix it will revert to the original "sample/test" code without any authorization at all and it's been frustrating, an epic waste of time.

**Comment by duhlink** [comment]
here is another example...

Error
TLS protocol version "TLSv1.2" conflicts with secureProtocol "TLS_method"
API Communication Log
REQUEST
22:51:35.722
{
  "method": "POST",
  "url": "/filemaker/test"
}
RESPONSE
22:51:49.862
{
  "status": 200,
  "data": {
    "status": "error",
    "message": "TLS protocol version \"TLSv1.2\" conflicts with secureProtocol \"TLS_method\""
  }
}

![CleanShot 2024-10-23 at 22 53 44](https://github.com/user-attachments/assets/0d6eed0b-296b-4d53-b12c-ed8779cb0713)
