### ISSUE TITLE
Unable to deploy Application

### ISSUE THREAD

**Issue by bitvercel** [stackblitz/bolt.new#940]
### Describe the bug

When I click on Deploy App it tries to build a vite but I think that's incorrect. Please let me know how to fix this.

❯ npx vite build
failed to load config from /home/project/vite.config.ts
error during build:
Error: Cannot find module '@vitejs/plugin-react'
Require stack:
- /home/project/vite.config.ts
- /home/.npm/_npx/9ed06546b0653f96/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js
    at Module._resolveFilename (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:12334)
    at Module._load (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:9839)
    at Module.require (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:13097)
    at require3 (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:163:2815)
    at _0x5bfa83 (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:792044)
    at Object.eval (file:///home/project/vite.config.ts#cjs:36:35)
    at Object._0x34b746 (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.34c588ed.js:40:792686)
    at Module._compile (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:14246)
    at _require.extensions.<computed> [as .js] (file:///home/.npm/_npx/9ed06546b0653f96/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:66752:16)
    at Module.load (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:144:12820)

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-wqkgec

### Steps to reproduce

simply deploy this prototype

### Expected behavior

It want it to deploy 

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
performance.memory = {
  "totalJSHeapSize": 260763499,
  "usedJSHeapSize": 251692999,
  "jsHeapSizeLimit": 4294705152
}
Username = bitvercel
Chat ID = 5be16e5b0c25
```

### Additional context

Error:
```
An error occured while streaming this message.
```

**Comment by kc0tlh** [comment]
@bitvercel this is being tracked in #1022
